# IPC-MPC Study: Complete Analysis Notebook

This is the primary, consolidated study notebook. Choose **Run → Run All Cells** to refresh the complete analysis in one place. It uses the cached adult hematologic-malignancy cohort and then runs every validated report-facing analysis from baseline characteristics through annual trends.

All results describe NIS hospitalizations rather than unique longitudinal patients. Report-facing tables include p-values and total or cohort-denominator rows.

In [1]:
from pathlib import Path
import json, os, sys
import pandas as pd
from IPython.display import Markdown, display

REPO_ROOT = Path.cwd()
if REPO_ROOT.name == 'notebooks':
    REPO_ROOT = REPO_ROOT.parent
if not (REPO_ROOT / 'src').is_dir():
    raise RuntimeError('Open this notebook from the IPC-MPC-Study repository.')
os.chdir(REPO_ROOT)
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
COHORT_DB = REPO_ROOT / 'outputs/phase_1_2/hm_cohort.duckdb'
if not COHORT_DB.exists():
    raise RuntimeError('The cached HM cohort is missing. Run src.phase_1_2 first.')
print(f'Repository: {REPO_ROOT}')
print(f'Cached cohort: {COHORT_DB}')

Repository: /Users/evelynzhang/Desktop/dev/IPC-MPC-Study
Cached cohort: /Users/evelynzhang/Desktop/dev/IPC-MPC-Study/outputs/phase_1_2/hm_cohort.duckdb

# Phase 1–2: Data Readiness and Adult HM Cohort

The validated aggregate files are loaded directly here. This avoids the two malformed pasted-output cells in the older Phase 1–2 notebook while preserving its actual cohort results.

In [2]:
phase12 = REPO_ROOT / 'outputs/phase_1_2'
phase12_tables = [
    ('Data-readiness audit', 'data_readiness_audit.csv'),
    ('Cohort overview', 'review_table_1_cohort_overview.csv'),
    ('Cohort by year', 'cohort_by_year.csv'),
    ('Mutually exclusive first-listed HM subtype', 'review_table_3_subtypes.csv'),
    ('HM subtype overlap', 'cohort_overlap.csv'),
    ('Hospital region', 'hospital_by_region.csv'),
    ('Hospital location/teaching', 'hospital_by_location_teaching.csv'),
    ('Hospital bed size', 'hospital_by_bed_size.csv'),
]
for title, filename in phase12_tables:
    display(Markdown(f'## {title}'))
    table = pd.read_csv(phase12 / filename, keep_default_na=False)
    display(table.style.hide(axis='index'))
    print('Copy/paste CSV:\n' + table.to_csv(index=False))

## Data-readiness audit

Copy/paste CSV:
component,status,detail
Diagnosis fields,READY,40 fields available
Adult cohort,READY,Requires AGE
Discharge weights,READY,Requires DISCWT
Survey strata,READY,Requires NIS_STRATUM
Mortality,READY,Requires DIED
Length of stay,READY,Requires LOS
Hospital characteristics,DERIVED/REVIEW,"Division, region, control, location/teaching, and bed size decoded from four-digit NIS_STRATUM"
Mechanical ventilation,OUT OF SCOPE,Removed from the requested analysis; procedure fields are not required

## Cohort overview

Copy/paste CSV:
cohort_measure,unweighted_n,weighted_n_2016_2022,weighted_percent
All adult HM discharges,994992,4974958.0,100.0
Documented sepsis (A41*),158421,792105.0,15.92
Documented inpatient palliative-care use (Z51.5),80733,403665.0,8.11
Multiple HM groups,44350,221750.0,4.46

## Cohort by year

Copy/paste CSV:
year,unweighted_hm_discharges,weighted_hm_discharges,unweighted_with_sepsis,weighted_sepsis_percent,unweighted_with_palliative_care,weighted_palliative_care_percent
2016,144171,720855.0,21442,14.87,9738,6.75
2017,143704,718520.0,21734,15.12,10435,7.26
2018,146473,732365.0,23098,15.77,11127,7.6
2019,153047,765235.0,24411,15.95,11817,7.72
2020,140796,703980.0,23786,16.89,12071,8.57
2021,141380,706899.0,23375,16.53,13119,9.28
2022,125421,627105.0,20575,16.4,12426,9.91

## Mutually exclusive first-listed HM subtype

Copy/paste CSV:
hm_subtype,unweighted_n,weighted_n_2016_2022,sepsis_unweighted_n,sepsis_weighted_percent,palliative_care_unweighted_n,palliative_care_weighted_percent
Lymphoma,301494,1507470.0,42749,14.18,23491,7.79
Myeloproliferative neoplasm,170226,851130.0,31995,18.8,8606,5.06
Multiple myeloma/plasma-cell neoplasm,150044,750220.0,22096,14.73,13580,9.05
CLL/chronic leukemia,108837,544185.0,17595,16.17,8272,7.6
Myelodysplastic disease,106324,531620.0,16745,15.75,9809,9.23
Acute myeloid leukemia,79382,396910.0,15820,19.93,10984,13.84
Acute lymphoblastic/unspecified acute leukemia,32145,160725.0,4348,13.53,2200,6.84
Chronic myeloid leukemia,26540,132700.0,3393,12.78,1760,6.63
Other leukemia,20000,100000.0,3680,18.4,2031,10.16

## HM subtype overlap

Copy/paste CSV:
hm_group_count,unweighted_hm_discharges,weighted_hm_discharges_2016_2022,weighted_percent
1,950642,4753208.0,95.54
2,42703,213515.0,4.29
3,1600,8000.0,0.16
4+,47,235.0,0.0

## Hospital region

Copy/paste CSV:
hospital_region,unweighted_hm_discharges,weighted_hm_discharges_2016_2022,weighted_percent
South,362561,1812805.0,36.44
Midwest,229923,1149615.0,23.11
Northeast,205522,1027610.0,20.66
West,196986,984929.0,19.8

## Hospital location/teaching

Copy/paste CSV:
hospital_location_teaching,unweighted_hm_discharges,weighted_hm_discharges_2016_2022,weighted_percent
Urban teaching,770042,3850209.0,77.39
Urban nonteaching,161686,808430.0,16.25
Rural,63264,316320.0,6.36

## Hospital bed size

Copy/paste CSV:
hospital_bed_size,unweighted_hm_discharges,weighted_hm_discharges_2016_2022,weighted_percent
Large,562251,2811256.0,56.51
Medium,255141,1275704.0,25.64
Small,177600,887999.0,17.85

# Phase 3: Baseline Characteristics

In [3]:
%run notebooks/phase_3_baseline_characteristics.ipynb

{
  "unit": "NIS inpatient discharge, not unique patient",
  "no_sepsis_unweighted_n": 836571,
  "no_sepsis_weighted_n": 4182853,
  "sepsis_unweighted_n": 158421,
  "sepsis_weighted_n": 792105,
  "age_no_sepsis_mean_sd": "66.84 (16.35)",
  "age_sepsis_mean_sd": "67.33 (15.61)",
  "largest_absolute_standardized_differences": [
    {
      "characteristic": "Hospital region (stratum-derived)",
      "level": "West",
      "standardized_difference": 0.102
    },
    {
      "characteristic": "HM subtype",
      "level": "Myeloproliferative neoplasm",
      "standardized_difference": 0.095
    },
    {
      "characteristic": "HM subtype",
      "level": "Lymphoma",
      "standardized_difference": -0.087
    },
    {
      "characteristic": "HM subtype",
      "level": "Acute myeloid leukemia",
      "standardized_difference": 0.084
    },
    {
      "characteristic": "Primary payer",
      "level": "Private insurance",
      "standardized_difference": -0.079
    },
    {
      "characteristic": "Hospital ownership/control (stratum-derived)",
      "level": "Government, nonfederal",
      "standardized_difference": -0.061
    },
    {
      "characteristic": "Sex",
      "level": "Male",
      "standardized_difference": 0.059
    },
    {
      "characteristic": "Sex",
      "level": "Female",
      "standardized_difference": -0.059
    }
  ],
  "limitations": [
    "Descriptive weighted estimates; no adjusted causal interpretation.",
    "HM and A41-only sepsis phenotypes remain draft pending investigator review.",
    "Hospital characteristics are decoded from NIS_STRATUM.",
    "Comorbidity burden is deferred until a validated Charlson or Elixhauser method is selected.",
    "P-values are approximate unadjusted tests based on sampled discharge counts and do not incorporate hospital clustering.",
    "Missing and unknown categories are displayed but excluded from categorical chi-square tests."
  ]
}

## Cohort sizes

                      group  unweighted_n  weighted_n_2016_2022
0      No documented sepsis        836571               4182853
1  Documented sepsis (A41*)        158421                792105
2                     Total        994992               4974958

Copy/paste CSV:
group,unweighted_n,weighted_n_2016_2022
No documented sepsis,836571,4182853
Documented sepsis (A41*),158421,792105
Total,994992,4974958

## Table 1. Weighted baseline characteristics by documented sepsis status

,characteristic,level,no_sepsis_unweighted_n,no_sepsis_weighted_n,no_sepsis_weighted_percent_or_mean_sd,sepsis_unweighted_n,sepsis_weighted_n,sepsis_weighted_percent_or_mean_sd,difference_percentage_points,standardized_difference,p_value
0,"Age, years",Weighted mean (SD),836571.0,4182853,66.84 (16.35),158421.0,792105,67.33 (15.61),NaN,0.031,<0.001
1,Age group,18–59,227633.0,1138165,27.21%,40925.0,204625,25.83%,-1.38,-0.031,<0.001
2,Age group,60 or older,608938.0,3044689,72.79%,117496.0,587480,74.17%,1.38,0.031,NaN
3,Sex,Male,457091.0,2285454,54.64%,91204.0,456020,57.57%,2.93,0.059,<0.001
4,Sex,Female,379264.0,1896319,45.34%,67187.0,335935,42.41%,-2.93,-0.059,NaN
5,Sex,Missing,216.0,1080,0.03%,30.0,150,0.02%,-0.01,-0.005,NaN
6,Race/ethnicity,White,589978.0,2949889,70.52%,107641.0,538205,67.95%,-2.58,-0.056,<0.001
7,Race/ethnicity,Black,102337.0,511685,12.23%,19933.0,99665,12.58%,0.35,0.011,NaN
8,Race/ethnicity,Hispanic,72158.0,360790,8.63%,15864.0,79320,10.01%,1.39,0.048,NaN
9,Race/ethnicity,Asian/Pacific Islander,22147.0,110735,2.65%,5375.0,26875,3.39%,0.75,0.044,NaN
10,Race/ethnicity,Native American,3288.0,16440,0.39%,800.0,4000,0.50%,0.11,0.017,NaN
11,Race/ethnicity,Other,24313.0,121565,2.91%,4784.0,23920,3.02%,0.11,0.007,NaN
12,Race/ethnicity,Missing,22350.0,111750,2.67%,4024.0,20120,2.54%,-0.13,-0.008,NaN
13,Primary payer,Medicare,516994.0,2584969,61.80%,101172.0,505860,63.86%,2.06,0.043,<0.001
14,Primary payer,Medicaid,81171.0,405855,9.70%,17348.0,86740,10.95%,1.25,0.041,NaN
15,Primary payer,Private insurance,196962.0,984810,23.54%,32156.0,160780,20.30%,-3.25,-0.079,NaN
16,Primary payer,Self-pay,17788.0,88940,2.13%,3285.0,16425,2.07%,-0.05,-0.004,NaN
17,Primary payer,No charge,2008.0,10040,0.24%,339.0,1695,0.21%,-0.03,-0.005,NaN
18,Primary payer,Other,20674.0,103370,2.47%,3957.0,19785,2.50%,0.03,0.002,NaN
19,Primary payer,Missing,974.0,4870,0.12%,164.0,820,0.10%,-0.01,-0.004,NaN
20,Median household-income quartile,0–25th percentile,204997.0,1024985,24.50%,40721.0,203605,25.70%,1.20,0.028,<0.001
21,Median household-income quartile,26th–50th percentile,207297.0,1036485,24.78%,38964.0,194820,24.60%,-0.18,-0.004,NaN
22,Median household-income quartile,51st–75th percentile,208642.0,1043210,24.94%,38606.0,193030,24.37%,-0.57,-0.013,NaN
23,Median household-income quartile,76th–100th percentile,202425.0,1012125,24.20%,37508.0,187540,23.68%,-0.52,-0.012,NaN
24,Median household-income quartile,Missing,13210.0,66050,1.58%,2622.0,13110,1.66%,0.08,0.006,NaN
25,HM subtype,Lymphoma,258745.0,1293725,30.93%,42749.0,213745,26.98%,-3.94,-0.087,<0.001
26,HM subtype,Acute myeloid leukemia,63562.0,317810,7.60%,15820.0,79100,9.99%,2.39,0.084,NaN
27,HM subtype,Chronic myeloid leukemia,23147.0,115735,2.77%,3393.0,16965,2.14%,-0.63,-0.04,NaN
28,HM subtype,CLL/chronic leukemia,91242.0,456210,10.91%,17595.0,87975,11.11%,0.20,0.006,NaN
29,HM subtype,Acute lymphoblastic/unspecified acute leukemia,27797.0,138985,3.32%,4348.0,21740,2.74%,-0.58,-0.034,NaN
30,HM subtype,Other leukemia,16320.0,81600,1.95%,3680.0,18400,2.32%,0.37,0.026,NaN
31,HM subtype,Multiple myeloma/plasma-cell neoplasm,127948.0,639740,15.29%,22096.0,110480,13.95%,-1.35,-0.038,NaN
32,HM subtype,Myelodysplastic disease,89579.0,447895,10.71%,16745.0,83725,10.57%,-0.14,-0.004,NaN
33,HM subtype,Myeloproliferative neoplasm,138231.0,691155,16.52%,31995.0,159975,20.20%,3.67,0.095,NaN
34,Hospital region (stratum-derived),Northeast,175549.0,877745,20.98%,29973.0,149865,18.92%,-2.06,-0.052,<0.001
35,Hospital region (stratum-derived),Midwest,195801.0,979005,23.41%,34122.0,170610,21.54%,-1.87,-0.045,NaN
36,Hospital region (stratum-derived),South,305152.0,1525760,36.48%,57409.0,287045,36.24%,-0.24,-0.005,NaN
37,Hospital region (stratum-derived),West,160069.0,800344,19.13%,36917.0,184585,23.30%,4.17,0.102,NaN
38,Hospital location/teaching (stratum-derived),Rural,53101.0,265505,6.35%,10163.0,50815,6.42%,0.07,0.003,<0.001
39,Hospital location/teaching (stratum-derived),Urban nonteaching,132999.0,664995,15.90%,28687.0,143435,18.11%,2.21,0.059,NaN
40,Hospital location/teaching (stratum-derived),Urban teaching,650471.0,3252354,77.75%,119571.0,597855,75.48%,-2.28,-0.054,NaN
41,Hospital bed size (stratum-derived),Small,148229.0,741144,17.72%,29371.0,146855,18.54%,0.82,0.021,<0.001
42,Hospital bed size (stratum-derived),Medium,211872.0,1059359,25.33%,43269.0,216345,27.31%,1.99,0.045,NaN
43,Hospital bed size (stratum-derived),Large,476470.0,2382351,56.96%,85781.0,428905,54.15%,-2.81,-0.057,NaN
44,Hospital ownership/control (stratum-derived),"Government, nonfederal",109420.0,547099,13.08%,17565.0,87825,11.09%,-1.99,-0.061,<0.001
45,Hospital ownership/control (stratum-derived),"Private, not-for-profit",643158.0,3215790,76.88%,122493.0,612465,77.32%,0.44,0.01,NaN
46,Hospital ownership/control (stratum-derived),"Private, investor-owned",83993.0,419965,10.04%,18363.0,91815,11.59%,1.55,0.05,NaN
47,Admission year,2016,122729.0,613645,14.67%,21442.0,107210,13.53%,-1.14,-0.033,<0.001
48,Admission year,2017,121970.0,609850,14.58%,21734.0,108670,13.72%,-0.86,-0.025,NaN
49,Admission year,2018,123375.0,616875,14.75%,23098.0,115490,14.58%,-0.17,-0.005,NaN
50,Admission year,2019,128636.0,643180,15.38%,24411.0,122055,15.41%,0.03,0.001,NaN
51,Admission year,2020,117010.0,585050,13.99%,23786.0,118930,15.01%,1.03,0.029,NaN
52,Admission year,2021,118005.0,590025,14.11%,23375.0,116875,14.75%,0.65,0.018,NaN
53,Admission year,2022,104846.0,524230,12.53%,20575.0,102875,12.99%,0.45,0.014,NaN
54,Total cohort denominator,,NaN,4182853,—,NaN,792105,—,NaN,—,—

Copy/paste CSV:
characteristic,level,no_sepsis_unweighted_n,no_sepsis_weighted_n,no_sepsis_weighted_percent_or_mean_sd,sepsis_unweighted_n,sepsis_weighted_n,sepsis_weighted_percent_or_mean_sd,difference_percentage_points,standardized_difference,p_value
"Age, years",Weighted mean (SD),836571.0,4182853,66.84 (16.35),158421.0,792105,67.33 (15.61),,0.031,<0.001
Age group,18–59,227633.0,1138165,27.21%,40925.0,204625,25.83%,-1.38,-0.031,<0.001
Age group,60 or older,608938.0,3044689,72.79%,117496.0,587480,74.17%,1.38,0.031,
Sex,Male,457091.0,2285454,54.64%,91204.0,456020,57.57%,2.93,0.059,<0.001
Sex,Female,379264.0,1896319,45.34%,67187.0,335935,42.41%,-2.93,-0.059,
Sex,Missing,216.0,1080,0.03%,30.0,150,0.02%,-0.01,-0.005,
Race/ethnicity,White,589978.0,2949889,70.52%,107641.0,538205,67.95%,-2.58,-0.056,<0.001
Race/ethnicity,Black,102337.0,511685,12.23%,19933.0,99665,12.58%,0.35,0.011,
Race/ethnicity,Hispanic,72158.0,360790,8.63%,15864.0,79320,10.01%,1.39,0.048,
Race/ethnicity,Asian/Pacific Islander,22147.0,110735,2.65%,5375.0,26875,3.39%,0.75,0.044,
Race/ethnicity,Native American,3288.0,16440,0.39%,800.0,4000,0.50%,0.11,0.017,
Race/ethnicity,Other,24313.0,121565,2.91%,4784.0,23920,3.02%,0.11,0.007,
Race/ethnicity,Missing,22350.0,111750,2.67%,4024.0,20120,2.54%,-0.13,-0.008,
Primary payer,Medicare,516994.0,2584969,61.80%,101172.0,505860,63.86%,2.06,0.043,<0.001
Primary payer,Medicaid,81171.0,405855,9.70%,17348.0,86740,10.95%,1.25,0.041,
Primary payer,Private insurance,196962.0,984810,23.54%,32156.0,160780,20.30%,-3.25,-0.079,
Primary payer,Self-pay,17788.0,88940,2.13%,3285.0,16425,2.07%,-0.05,-0.004,
Primary payer,No charge,2008.0,10040,0.24%,339.0,1695,0.21%,-0.03,-0.005,
Primary payer,Other,20674.0,103370,2.47%,3957.0,19785,2.50%,0.03,0.002,
Primary payer,Missing,974.0,4870,0.12%,164.0,820,0.10%,-0.01,-0.004,
Median household-income quartile,0–25th percentile,204997.0,1024985,24.50%,40721.0,203605,25.70%,1.2,0.028,<0.001
Median household-income quartile,26th–50th percentile,207297.0,1036485,24.78%,38964.0,194820,24.60%,-0.18,-0.004,
Median household-income quartile,51st–75th percentile,208642.0,1043210,24.94%,38606.0,193030,24.37%,-0.57,-0.013,
Median household-income quartile,76th–100th percentile,202425.0,1012125,24.20%,37508.0,187540,23.68%,-0.52,-0.012,
Median household-income quartile,Missing,13210.0,66050,1.58%,2622.0,13110,1.66%,0.08,0.006,
HM subtype,Lymphoma,258745.0,1293725,30.93%,42749.0,213745,26.98%,-3.94,-0.087,<0.001
HM subtype,Acute myeloid leukemia,63562.0,317810,7.60%,15820.0,79100,9.99%,2.39,0.084,
HM subtype,Chronic myeloid leukemia,23147.0,115735,2.77%,3393.0,16965,2.14%,-0.63,-0.04,
HM subtype,CLL/chronic leukemia,91242.0,456210,10.91%,17595.0,87975,11.11%,0.2,0.006,
HM subtype,Acute lymphoblastic/unspecified acute leukemia,27797.0,138985,3.32%,4348.0,21740,2.74%,-0.58,-0.034,
HM subtype,Other leukemia,16320.0,81600,1.95%,3680.0,18400,2.32%,0.37,0.026,
HM subtype,Multiple myeloma/plasma-cell neoplasm,127948.0,639740,15.29%,22096.0,110480,13.95%,-1.35,-0.038,
HM subtype,Myelodysplastic disease,89579.0,447895,10.71%,16745.0,83725,10.57%,-0.14,-0.004,
HM subtype,Myeloproliferative neoplasm,138231.0,691155,16.52%,31995.0,159975,20.20%,3.67,0.095,
Hospital region (stratum-derived),Northeast,175549.0,877745,20.98%,29973.0,149865,18.92%,-2.06,-0.052,<0.001
Hospital region (stratum-derived),Midwest,195801.0,979005,23.41%,34122.0,170610,21.54%,-1.87,-0.045,
Hospital region (stratum-derived),South,305152.0,1525760,36.48%,57409.0,287045,36.24%,-0.24,-0.005,
Hospital region (stratum-derived),West,160069.0,800344,19.13%,36917.0,184585,23.30%,4.17,0.102,
Hospital location/teaching (stratum-derived),Rural,53101.0,265505,6.35%,10163.0,50815,6.42%,0.07,0.003,<0.001
Hospital location/teaching (stratum-derived),Urban nonteaching,132999.0,664995,15.90%,28687.0,143435,18.11%,2.21,0.059,
Hospital location/teaching (stratum-derived),Urban teaching,650471.0,3252354,77.75%,119571.0,597855,75.48%,-2.28,-0.054,
Hospital bed size (stratum-derived),Small,148229.0,741144,17.72%,29371.0,146855,18.54%,0.82,0.021,<0.001
Hospital bed size (stratum-derived),Medium,211872.0,1059359,25.33%,43269.0,216345,27.31%,1.99,0.045,
Hospital bed size (stratum-derived),Large,476470.0,2382351,56.96%,85781.0,428905,54.15%,-2.81,-0.057,
Hospital ownership/control (stratum-derived),"Government, nonfederal",109420.0,547099,13.08%,17565.0,87825,11.09%,-1.99,-0.061,<0.001
Hospital ownership/control (stratum-derived),"Private, not-for-profit",643158.0,3215790,76.88%,122493.0,612465,77.32%,0.44,0.01,
Hospital ownership/control (stratum-derived),"Private, investor-owned",83993.0,419965,10.04%,18363.0,91815,11.59%,1.55,0.05,
Admission year,2016,122729.0,613645,14.67%,21442.0,107210,13.53%,-1.14,-0.033,<0.001
Admission year,2017,121970.0,609850,14.58%,21734.0,108670,13.72%,-0.86,-0.025,
Admission year,2018,123375.0,616875,14.75%,23098.0,115490,14.58%,-0.17,-0.005,
Admission year,2019,128636.0,643180,15.38%,24411.0,122055,15.41%,0.03,0.001,
Admission year,2020,117010.0,585050,13.99%,23786.0,118930,15.01%,1.03,0.029,
Admission year,2021,118005.0,590025,14.11%,23375.0,116875,14.75%,0.65,0.018,
Admission year,2022,104846.0,524230,12.53%,20575.0,102875,12.99%,0.45,0.014,
Total cohort denominator,,,4182853,—,,792105,—,,—,—

## Missingness review

,characteristic,no_sepsis_missing_unweighted_n,no_sepsis_missing_weighted_percent,sepsis_missing_unweighted_n,sepsis_missing_weighted_percent
0,Age group,0,0.00,0,0.00
1,Sex,216,0.03,30,0.02
2,Race/ethnicity,22350,2.67,4024,2.54
3,Primary payer,974,0.12,164,0.10
4,Median household-income quartile,13210,1.58,2622,1.66
5,HM subtype,0,0.00,0,0.00
6,Hospital region (stratum-derived),0,0.00,0,0.00
7,Hospital location/teaching (stratum-derived),0,0.00,0,0.00
8,Hospital bed size (stratum-derived),0,0.00,0,0.00
9,Hospital ownership/control (stratum-derived),0,0.00,0,0.00
10,Admission year,0,0.00,0,0.00

Copy/paste CSV:
characteristic,no_sepsis_missing_unweighted_n,no_sepsis_missing_weighted_percent,sepsis_missing_unweighted_n,sepsis_missing_weighted_percent
Age group,0,0.0,0,0.0
Sex,216,0.03,30,0.02
Race/ethnicity,22350,2.67,4024,2.54
Primary payer,974,0.12,164,0.1
Median household-income quartile,13210,1.58,2622,1.66
HM subtype,0,0.0,0,0.0
Hospital region (stratum-derived),0,0.0,0,0.0
Hospital location/teaching (stratum-derived),0,0.0,0,0.0
Hospital bed size (stratum-derived),0,0.0,0,0.0
Hospital ownership/control (stratum-derived),0,0.0,0,0.0
Admission year,0,0.0,0,0.0

## Largest descriptive differences

,characteristic,level,standardized_difference
0,Hospital region (stratum-derived),West,0.102
1,HM subtype,Myeloproliferative neoplasm,0.095
2,HM subtype,Lymphoma,-0.087
3,HM subtype,Acute myeloid leukemia,0.084
4,Primary payer,Private insurance,-0.079
5,Hospital ownership/control (stratum-derived),"Government, nonfederal",-0.061
6,Sex,Male,0.059
7,Sex,Female,-0.059

Copy/paste CSV:
characteristic,level,standardized_difference
Hospital region (stratum-derived),West,0.102
HM subtype,Myeloproliferative neoplasm,0.095
HM subtype,Lymphoma,-0.087
HM subtype,Acute myeloid leukemia,0.084
Primary payer,Private insurance,-0.079
Hospital ownership/control (stratum-derived),"Government, nonfederal",-0.061
Sex,Male,0.059
Sex,Female,-0.059

### Copy/paste report text

The draft cohort contained 994,992 sampled adult hematologic-malignancy inpatient discharges from 2016–2022. Documented sepsis was present in 158,421 sampled discharges and absent in 836,571. The corresponding cumulative weighted discharge estimates were 792,105 and 4,182,853, respectively. Mean age was 67.33 (15.61) years among discharges with documented sepsis and 66.84 (16.35) years among discharges without documented sepsis. Baseline characteristics are descriptive and should not be interpreted causally.

### Copy/paste report text

The draft cohort contained 994,992 sampled adult hematologic-malignancy inpatient discharges from 2016–2022. Documented sepsis was present in 158,421 sampled discharges and absent in 836,571. The corresponding cumulative weighted discharge estimates were 792,105 and 4,182,853, respectively. Mean age was 67.33 (15.61) years among discharges with documented sepsis and 66.84 (16.35) years among discharges without documented sepsis. Baseline characteristics are descriptive and should not be interpreted causally.

# Phase 4: Co-Documented Complications

In [4]:
%run notebooks/phase_4_complications.ipynb

{
  "unit": "NIS inpatient discharge, not unique patient",
  "exposure": "Documented sepsis defined by A41* in any diagnosis position",
  "interpretation": "Complications are co-documented during the same hospitalization; temporal order is not available.",
  "inference_note": "P-values use unweighted sampled discharge counts and do not account for hospital clustering; FDR-adjusted values control multiplicity across the displayed complication comparisons.",
  "no_sepsis_unweighted_n": 836571,
  "sepsis_unweighted_n": 158421,
  "largest_absolute_differences": [
    {
      "complication": "Severe sepsis, with or without shock",
      "no_sepsis_unweighted_n": 3692,
      "no_sepsis_weighted_n": 18460,
      "no_sepsis_weighted_percent": 0.44,
      "sepsis_unweighted_n": 67538,
      "sepsis_weighted_n": 337690,
      "sepsis_weighted_percent": 42.63,
      "absolute_difference_percentage_points": 42.19,
      "prevalence_ratio": 96.6,
      "p_value_unadjusted": "<0.001",
      "p_value_fdr_adjusted": "<0.001",
      "fdr_significant_at_0_05": true
    },
    {
      "complication": "Pneumonia",
      "no_sepsis_unweighted_n": 102930,
      "no_sepsis_weighted_n": 514650,
      "no_sepsis_weighted_percent": 12.3,
      "sepsis_unweighted_n": 63040,
      "sepsis_weighted_n": 315200,
      "sepsis_weighted_percent": 39.79,
      "absolute_difference_percentage_points": 27.49,
      "prevalence_ratio": 3.23,
      "p_value_unadjusted": "<0.001",
      "p_value_fdr_adjusted": "<0.001",
      "fdr_significant_at_0_05": true
    },
    {
      "complication": "Severe sepsis with septic shock",
      "no_sepsis_unweighted_n": 2134,
      "no_sepsis_weighted_n": 10670,
      "no_sepsis_weighted_percent": 0.26,
      "sepsis_unweighted_n": 41137,
      "sepsis_weighted_n": 205685,
      "sepsis_weighted_percent": 25.97,
      "absolute_difference_percentage_points": 25.71,
      "prevalence_ratio": 101.8,
      "p_value_unadjusted": "<0.001",
      "p_value_fdr_adjusted": "<0.001",
      "fdr_significant_at_0_05": true
    },
    {
      "complication": "Acute kidney injury",
      "no_sepsis_unweighted_n": 184124,
      "no_sepsis_weighted_n": 920620,
      "no_sepsis_weighted_percent": 22.01,
      "sepsis_unweighted_n": 70212,
      "sepsis_weighted_n": 351060,
      "sepsis_weighted_percent": 44.32,
      "absolute_difference_percentage_points": 22.31,
      "prevalence_ratio": 2.01,
      "p_value_unadjusted": "<0.001",
      "p_value_fdr_adjusted": "<0.001",
      "fdr_significant_at_0_05": true
    },
    {
      "complication": "Acute respiratory failure",
      "no_sepsis_unweighted_n": 72064,
      "no_sepsis_weighted_n": 360320,
      "no_sepsis_weighted_percent": 8.61,
      "sepsis_unweighted_n": 47094,
      "sepsis_weighted_n": 235470,
      "sepsis_weighted_percent": 29.73,
      "absolute_difference_percentage_points": 21.11,
      "prevalence_ratio": 3.45,
      "p_value_unadjusted": "<0.001",
      "p_value_fdr_adjusted": "<0.001",
      "fdr_significant_at_0_05": true
    }
  ]
}

## Table. Co-documented complications by sepsis status

,complication,no_sepsis_unweighted_n,no_sepsis_weighted_n,no_sepsis_weighted_percent,sepsis_unweighted_n,sepsis_weighted_n,sepsis_weighted_percent,absolute_difference_percentage_points,prevalence_ratio,p_value_unadjusted,p_value_fdr_adjusted,fdr_significant_at_0_05
0,Severe sepsis with septic shock,2134,10670,0.26,41137,205685,25.97,25.71,101.8,<0.001,<0.001,True
1,"Severe sepsis, with or without shock",3692,18460,0.44,67538,337690,42.63,42.19,96.6,<0.001,<0.001,True
2,Acute respiratory failure,72064,360320,8.61,47094,235470,29.73,21.11,3.45,<0.001,<0.001,True
3,"Respiratory failure, unspecified",5289,26445,0.63,2797,13985,1.77,1.13,2.79,<0.001,<0.001,True
4,Acute kidney injury,184124,920620,22.01,70212,351060,44.32,22.31,2.01,<0.001,<0.001,True
5,Pneumonia,102930,514650,12.3,63040,315200,39.79,27.49,3.23,<0.001,<0.001,True
6,Pulmonary embolism,15824,79120,1.89,3395,16975,2.14,0.25,1.13,<0.001,<0.001,True
7,Acute lower-extremity DVT,7160,35800,0.86,1695,8475,1.07,0.21,1.25,<0.001,<0.001,True
8,Tumor lysis syndrome,11841,59205,1.42,3942,19710,2.49,1.07,1.76,<0.001,<0.001,True
9,Disseminated intravascular coagulation,3795,18975,0.45,3072,15360,1.94,1.49,4.27,<0.001,<0.001,True
10,Paroxysmal tachycardia/SVT/VT,26985,134925,3.23,9832,49160,6.21,2.98,1.92,<0.001,<0.001,True
11,"Atrial fibrillation/flutter, excluding chronic AF",145281,726405,17.37,34061,170305,21.5,4.13,1.24,<0.001,<0.001,True
12,Other cardiac arrhythmias,20641,103205,2.47,3723,18615,2.35,-0.12,0.95,0.006,0.006,True
13,Any specified cardiac arrhythmia,172215,861075,20.59,41803,209015,26.39,5.8,1.28,<0.001,<0.001,True
14,Total cohort denominator,836571,"4,182,853",100.00,158421,"792,105",100.00,—,—,—,—,—

Copy/paste CSV:
complication,no_sepsis_unweighted_n,no_sepsis_weighted_n,no_sepsis_weighted_percent,sepsis_unweighted_n,sepsis_weighted_n,sepsis_weighted_percent,absolute_difference_percentage_points,prevalence_ratio,p_value_unadjusted,p_value_fdr_adjusted,fdr_significant_at_0_05
Severe sepsis with septic shock,2134,10670,0.26,41137,205685,25.97,25.71,101.8,<0.001,<0.001,True
"Severe sepsis, with or without shock",3692,18460,0.44,67538,337690,42.63,42.19,96.6,<0.001,<0.001,True
Acute respiratory failure,72064,360320,8.61,47094,235470,29.73,21.11,3.45,<0.001,<0.001,True
"Respiratory failure, unspecified",5289,26445,0.63,2797,13985,1.77,1.13,2.79,<0.001,<0.001,True
Acute kidney injury,184124,920620,22.01,70212,351060,44.32,22.31,2.01,<0.001,<0.001,True
Pneumonia,102930,514650,12.3,63040,315200,39.79,27.49,3.23,<0.001,<0.001,True
Pulmonary embolism,15824,79120,1.89,3395,16975,2.14,0.25,1.13,<0.001,<0.001,True
Acute lower-extremity DVT,7160,35800,0.86,1695,8475,1.07,0.21,1.25,<0.001,<0.001,True
Tumor lysis syndrome,11841,59205,1.42,3942,19710,2.49,1.07,1.76,<0.001,<0.001,True
Disseminated intravascular coagulation,3795,18975,0.45,3072,15360,1.94,1.49,4.27,<0.001,<0.001,True
Paroxysmal tachycardia/SVT/VT,26985,134925,3.23,9832,49160,6.21,2.98,1.92,<0.001,<0.001,True
"Atrial fibrillation/flutter, excluding chronic AF",145281,726405,17.37,34061,170305,21.5,4.13,1.24,<0.001,<0.001,True
Other cardiac arrhythmias,20641,103205,2.47,3723,18615,2.35,-0.12,0.95,0.006,0.006,True
Any specified cardiac arrhythmia,172215,861075,20.59,41803,209015,26.39,5.8,1.28,<0.001,<0.001,True
Total cohort denominator,836571,"4,182,853",100.00,158421,"792,105",100.00,—,—,—,—,—

## Largest absolute prevalence differences

,complication,no_sepsis_weighted_percent,sepsis_weighted_percent,absolute_difference_percentage_points
0,"Severe sepsis, with or without shock",0.44,42.63,42.19
1,Pneumonia,12.3,39.79,27.49
2,Severe sepsis with septic shock,0.26,25.97,25.71
3,Acute kidney injury,22.01,44.32,22.31
4,Acute respiratory failure,8.61,29.73,21.11
5,Total cohort denominator,100.00,100.00,—

## Copy/paste interpretation

Among adult hematologic-malignancy inpatient discharges, the largest absolute difference among the evaluated co-documented complications was observed for severe sepsis, with or without shock: 42.63% among discharges with documented sepsis versus 0.44% among discharges without documented sepsis, an absolute difference of 42.19 percentage points. These diagnosis-based findings do not establish whether a complication preceded or followed sepsis.

## Copy/paste interpretation

Among adult hematologic-malignancy inpatient discharges, the largest absolute difference among the evaluated co-documented complications was observed for severe sepsis, with or without shock: 42.63% among discharges with documented sepsis versus 0.44% among discharges without documented sepsis, an absolute difference of 42.19 percentage points. These diagnosis-based findings do not establish whether a complication preceded or followed sepsis.

# Phase 5: Charlson Index, Length of Stay, and Mortality

In [5]:
%run notebooks/phase_5_cci_los_mortality.ipynb

{
  "unit": "NIS inpatient discharge, not unique patient",
  "cci_definition": "Quan ICD-10 mapping; original Charlson weights; cancer and metastatic cancer excluded; no age points; hierarchy applied.",
  "inference_note": "Descriptive values use DISCWT. P-values use sampled discharge counts and do not account for hospital clustering.",
  "no_sepsis_unweighted_n": 836571,
  "sepsis_unweighted_n": 158421,
  "los_missing": {
    "no_sepsis": 17,
    "sepsis": 7
  },
  "died_missing": {
    "no_sepsis": 375,
    "sepsis": 66
  },
  "table": [
    {
      "outcome": "Charlson Comorbidity Index excluding cancer",
      "level": "Mean (SD)",
      "no_sepsis": "1.84 (1.90)",
      "sepsis": "2.09 (1.92)",
      "p_value": "<0.001",
      "test": "Welch t-test"
    },
    {
      "outcome": "Charlson category",
      "level": "0",
      "no_sepsis": "1,319,600 (31.55%)",
      "sepsis": "190,300 (24.02%)",
      "p_value": "<0.001",
      "test": "Pearson chi-square"
    },
    {
      "outcome": "",
      "level": "1\u20132",
      "no_sepsis": "1,616,779 (38.65%)",
      "sepsis": "327,450 (41.34%)",
      "p_value": "",
      "test": ""
    },
    {
      "outcome": "",
      "level": "\u22653",
      "no_sepsis": "1,246,475 (29.80%)",
      "sepsis": "274,355 (34.64%)",
      "p_value": "",
      "test": ""
    },
    {
      "outcome": "Length of stay, days",
      "level": "Mean (SD)",
      "no_sepsis": "6.88 (8.20)",
      "sepsis": "11.13 (13.45)",
      "p_value": "<0.001",
      "test": "Welch t-test"
    },
    {
      "outcome": "In-hospital mortality",
      "level": "Died",
      "no_sepsis": "132,635 (3.17%)",
      "sepsis": "136,050 (17.18%)",
      "p_value": "<0.001",
      "test": "Pearson chi-square"
    }
  ],
  "unweighted_table": [
    {
      "outcome": "Charlson Comorbidity Index excluding cancer",
      "level": "Mean (SD)",
      "no_sepsis": "1.84 (1.90)",
      "sepsis": "2.09 (1.92)",
      "p_value": "<0.001",
      "test": "Welch t-test"
    },
    {
      "outcome": "Charlson category",
      "level": "0",
      "no_sepsis": "263,920 (31.55%)",
      "sepsis": "38,060 (24.02%)",
      "p_value": "<0.001",
      "test": "Pearson chi-square"
    },
    {
      "outcome": "",
      "level": "1\u20132",
      "no_sepsis": "323,356 (38.65%)",
      "sepsis": "65,490 (41.34%)",
      "p_value": "",
      "test": ""
    },
    {
      "outcome": "",
      "level": "\u22653",
      "no_sepsis": "249,295 (29.80%)",
      "sepsis": "54,871 (34.64%)",
      "p_value": "",
      "test": ""
    },
    {
      "outcome": "Length of stay, days",
      "level": "Mean (SD)",
      "no_sepsis": "6.88 (8.20)",
      "sepsis": "11.13 (13.45)",
      "p_value": "<0.001",
      "test": "Welch t-test"
    },
    {
      "outcome": "In-hospital mortality",
      "level": "Died",
      "no_sepsis": "26,527 (3.17%)",
      "sepsis": "27,210 (17.18%)",
      "p_value": "<0.001",
      "test": "Pearson chi-square"
    }
  ]
}

## Weighted national estimates

| Outcome | Level | No sepsis | Sepsis | P-value | Test |
|---|---|---|---|---|---|
| Charlson Comorbidity Index excluding cancer | Mean (SD) | 1.84 (1.90) | 2.09 (1.92) | <0.001 | Welch t-test |
| Charlson category | 0 | 1,319,600 (31.55%) | 190,300 (24.02%) | <0.001 | Pearson chi-square |
|  | 1–2 | 1,616,779 (38.65%) | 327,450 (41.34%) |  |  |
|  | ≥3 | 1,246,475 (29.80%) | 274,355 (34.64%) |  |  |
| Length of stay, days | Mean (SD) | 6.88 (8.20) | 11.13 (13.45) | <0.001 | Welch t-test |
| In-hospital mortality | Died | 132,635 (3.17%) | 136,050 (17.18%) | <0.001 | Pearson chi-square |
| Total cohort denominator |  | 4,182,853 (100.00%) | 792,105 (100.00%) | — | — |

## Unweighted sample results

| Outcome | Level | No sepsis | Sepsis | P-value | Test |
|---|---|---|---|---|---|
| Charlson Comorbidity Index excluding cancer | Mean (SD) | 1.84 (1.90) | 2.09 (1.92) | <0.001 | Welch t-test |
| Charlson category | 0 | 263,920 (31.55%) | 38,060 (24.02%) | <0.001 | Pearson chi-square |
|  | 1–2 | 323,356 (38.65%) | 65,490 (41.34%) |  |  |
|  | ≥3 | 249,295 (29.80%) | 54,871 (34.64%) |  |  |
| Length of stay, days | Mean (SD) | 6.88 (8.20) | 11.13 (13.45) | <0.001 | Welch t-test |
| In-hospital mortality | Died | 26,527 (3.17%) | 27,210 (17.18%) | <0.001 | Pearson chi-square |
| Total cohort denominator |  | 836,571 (100.00%) | 158,421 (100.00%) | — | — |

# Phase 6: Palliative-Care Prevalence and Annual Utilization

In [6]:
%run notebooks/phase_6_palliative_care.ipynb

{
  "definition": "Documented inpatient palliative-care use: normalized Z51.5 (Z515) in any diagnosis position.",
  "normalization": "Uppercase; decimal points and spaces removed in the Phase 1\u20132 cohort build.",
  "records_excluded_for_missing_weight_or_stratum": 0,
  "normalization_validation": {
    "flagged_records": 80733,
    "records_containing_normalized_Z515": 80733,
    "discordant_records": 0
  },
  "variance_note": "NIS_STRATUM and year-specific strata used in Taylor linearization; sampled discharges are variance units because HOSP_NIS is unavailable by study decision. Not a full NIS design variance estimate.",
  "prevalence_table": [
    {
      "cohort": "All adult HM hospitalizations",
      "unweighted_sample_n": 994992,
      "unweighted_palliative_care_n": 80733,
      "weighted_hospitalizations": 4974958,
      "weighted_palliative_care_n": 403665,
      "weighted_palliative_care_percent": 8.11,
      "ci_95_lower_percent": 8.06,
      "ci_95_upper_percent": 8.17
    },
    {
      "cohort": "HM without documented sepsis",
      "unweighted_sample_n": 836571,
      "unweighted_palliative_care_n": 54772,
      "weighted_hospitalizations": 4182853,
      "weighted_palliative_care_n": 273860,
      "weighted_palliative_care_percent": 6.55,
      "ci_95_lower_percent": 6.49,
      "ci_95_upper_percent": 6.6
    },
    {
      "cohort": "HM with documented sepsis",
      "unweighted_sample_n": 158421,
      "unweighted_palliative_care_n": 25961,
      "weighted_hospitalizations": 792105,
      "weighted_palliative_care_n": 129805,
      "weighted_palliative_care_percent": 16.39,
      "ci_95_lower_percent": 16.21,
      "ci_95_upper_percent": 16.57
    }
  ],
  "annual_prevalence_table": [
    {
      "year": 2016,
      "sepsis_status": "No documented sepsis",
      "unweighted_sample_n": 122729,
      "unweighted_palliative_care_n": 6750,
      "weighted_hospitalizations": 613645,
      "weighted_palliative_care_n": 33750,
      "weighted_palliative_care_percent": 5.5,
      "ci_95_lower_percent": 5.37,
      "ci_95_upper_percent": 5.63,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2016,
      "sepsis_status": "Documented sepsis",
      "unweighted_sample_n": 21442,
      "unweighted_palliative_care_n": 2988,
      "weighted_hospitalizations": 107210,
      "weighted_palliative_care_n": 14940,
      "weighted_palliative_care_percent": 13.94,
      "ci_95_lower_percent": 13.48,
      "ci_95_upper_percent": 14.41,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2017,
      "sepsis_status": "No documented sepsis",
      "unweighted_sample_n": 121970,
      "unweighted_palliative_care_n": 7229,
      "weighted_hospitalizations": 609850,
      "weighted_palliative_care_n": 36145,
      "weighted_palliative_care_percent": 5.93,
      "ci_95_lower_percent": 5.8,
      "ci_95_upper_percent": 6.06,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2017,
      "sepsis_status": "Documented sepsis",
      "unweighted_sample_n": 21734,
      "unweighted_palliative_care_n": 3206,
      "weighted_hospitalizations": 108670,
      "weighted_palliative_care_n": 16030,
      "weighted_palliative_care_percent": 14.75,
      "ci_95_lower_percent": 14.29,
      "ci_95_upper_percent": 15.23,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2018,
      "sepsis_status": "No documented sepsis",
      "unweighted_sample_n": 123375,
      "unweighted_palliative_care_n": 7507,
      "weighted_hospitalizations": 616875,
      "weighted_palliative_care_n": 37535,
      "weighted_palliative_care_percent": 6.08,
      "ci_95_lower_percent": 5.95,
      "ci_95_upper_percent": 6.22,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2018,
      "sepsis_status": "Documented sepsis",
      "unweighted_sample_n": 23098,
      "unweighted_palliative_care_n": 3620,
      "weighted_hospitalizations": 115490,
      "weighted_palliative_care_n": 18100,
      "weighted_palliative_care_percent": 15.67,
      "ci_95_lower_percent": 15.21,
      "ci_95_upper_percent": 16.15,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2019,
      "sepsis_status": "No documented sepsis",
      "unweighted_sample_n": 128636,
      "unweighted_palliative_care_n": 8021,
      "weighted_hospitalizations": 643180,
      "weighted_palliative_care_n": 40105,
      "weighted_palliative_care_percent": 6.24,
      "ci_95_lower_percent": 6.1,
      "ci_95_upper_percent": 6.37,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2019,
      "sepsis_status": "Documented sepsis",
      "unweighted_sample_n": 24411,
      "unweighted_palliative_care_n": 3796,
      "weighted_hospitalizations": 122055,
      "weighted_palliative_care_n": 18980,
      "weighted_palliative_care_percent": 15.55,
      "ci_95_lower_percent": 15.1,
      "ci_95_upper_percent": 16.01,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2020,
      "sepsis_status": "No documented sepsis",
      "unweighted_sample_n": 117010,
      "unweighted_palliative_care_n": 8019,
      "weighted_hospitalizations": 585050,
      "weighted_palliative_care_n": 40095,
      "weighted_palliative_care_percent": 6.85,
      "ci_95_lower_percent": 6.71,
      "ci_95_upper_percent": 7.0,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2020,
      "sepsis_status": "Documented sepsis",
      "unweighted_sample_n": 23786,
      "unweighted_palliative_care_n": 4052,
      "weighted_hospitalizations": 118930,
      "weighted_palliative_care_n": 20260,
      "weighted_palliative_care_percent": 17.04,
      "ci_95_lower_percent": 16.56,
      "ci_95_upper_percent": 17.52,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2021,
      "sepsis_status": "No documented sepsis",
      "unweighted_sample_n": 118005,
      "unweighted_palliative_care_n": 8800,
      "weighted_hospitalizations": 590025,
      "weighted_palliative_care_n": 44000,
      "weighted_palliative_care_percent": 7.46,
      "ci_95_lower_percent": 7.31,
      "ci_95_upper_percent": 7.61,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2021,
      "sepsis_status": "Documented sepsis",
      "unweighted_sample_n": 23375,
      "unweighted_palliative_care_n": 4319,
      "weighted_hospitalizations": 116875,
      "weighted_palliative_care_n": 21595,
      "weighted_palliative_care_percent": 18.48,
      "ci_95_lower_percent": 17.99,
      "ci_95_upper_percent": 18.98,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2022,
      "sepsis_status": "No documented sepsis",
      "unweighted_sample_n": 104846,
      "unweighted_palliative_care_n": 8446,
      "weighted_hospitalizations": 524230,
      "weighted_palliative_care_n": 42230,
      "weighted_palliative_care_percent": 8.06,
      "ci_95_lower_percent": 7.89,
      "ci_95_upper_percent": 8.22,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    },
    {
      "year": 2022,
      "sepsis_status": "Documented sepsis",
      "unweighted_sample_n": 20575,
      "unweighted_palliative_care_n": 3980,
      "weighted_hospitalizations": 102875,
      "weighted_palliative_care_n": 19900,
      "weighted_palliative_care_percent": 19.34,
      "ci_95_lower_percent": 18.81,
      "ci_95_upper_percent": 19.89,
      "sepsis_vs_no_sepsis_p_value": "<0.001"
    }
  ],
  "comparison": {
    "absolute_difference_percentage_points": 9.84,
    "difference_ci_95_lower": 9.65,
    "difference_ci_95_upper": 10.03,
    "strata_adjusted_p_value": "<0.001",
    "crude_weighted_odds_ratio": 2.798,
    "odds_ratio_ci_95_lower": 2.753,
    "odds_ratio_ci_95_upper": 2.842,
    "odds_ratio_p_value": "<0.001"
  },
  "adjusted_probabilities_note": "Covariate-adjusted probabilities require the later multivariable model (Command 16B) and are not estimated in this unadjusted Task 12B analysis."
}

## Documented inpatient palliative-care use

| Cohort | Unweighted sample n | Unweighted palliative-care n | Weighted hospitalizations | Weighted palliative-care n | Weighted palliative-care % | 95% CI lower, % | 95% CI upper, % |
|---|---|---|---|---|---|---|---|
| All adult HM hospitalizations | 994992 | 80733 | 4974958 | 403665 | 8.11 | 8.06 | 8.17 |
| HM without documented sepsis | 836571 | 54772 | 4182853 | 273860 | 6.55 | 6.49 | 6.6 |
| HM with documented sepsis | 158421 | 25961 | 792105 | 129805 | 16.39 | 16.21 | 16.57 |
| Total unique HM cohort | 994992 | 80733 | 4974958 | 403665 | 8.11 | 8.06 | 8.17 |

## Unadjusted sepsis comparison

| Measure | Estimate | 95% CI | P-value |
|---|---|---|---|
| Absolute prevalence difference, percentage points | 9.84 | 9.65 to 10.03 | <0.001 |
| Crude weighted odds ratio: sepsis vs no sepsis | 2.798 | 2.753 to 2.842 | <0.001 |
| Total (measures are not additive) | — | — | — |

## Annual utilization by sepsis status

| Year | No sepsis, weighted % (95% CI) | Sepsis, weighted % (95% CI) | P-value |
|---|---|---|---|
| 2016 | 5.50% (5.37%–5.63%) | 13.94% (13.48%–14.41%) | <0.001 |
| 2017 | 5.93% (5.80%–6.06%) | 14.75% (14.29%–15.23%) | <0.001 |
| 2018 | 6.08% (5.95%–6.22%) | 15.67% (15.21%–16.15%) | <0.001 |
| 2019 | 6.24% (6.10%–6.37%) | 15.55% (15.10%–16.01%) | <0.001 |
| 2020 | 6.85% (6.71%–7.00%) | 17.04% (16.56%–17.52%) | <0.001 |
| 2021 | 7.46% (7.31%–7.61%) | 18.48% (17.99%–18.98%) | <0.001 |
| 2022 | 8.06% (7.89%–8.22%) | 19.34% (18.81%–19.89%) | <0.001 |
| Total, 2016–2022 | 6.55% (6.49%–6.60%) | 16.39% (16.21%–16.57%) | <0.001 |

# Phase 7: Palliative-Care Use by HM Subtype

In [7]:
%run notebooks/phase_7_subtype_palliative_care.ipynb

{
  "definition": "Documented inpatient palliative-care use: normalized Z51.5 (Z515) in any diagnosis position.",
  "subtype_assignment": "Mutually exclusive first-listed qualifying HM subtype; overlaps retained in multiple_hm_groups for sensitivity analysis.",
  "records_excluded_for_missing_weight_stratum_or_subtype": 0,
  "variance_note": "Year-specific NIS_STRATUM used in Taylor linearization; sampled discharges are variance units because HOSP_NIS is unavailable by study decision. Not a full NIS design variance estimate.",
  "overall_tests": [
    {
      "cohort": "All adult HM hospitalizations",
      "wald_chi_square": 5835.404,
      "degrees_of_freedom": 8,
      "overall_p_value": "<0.001"
    },
    {
      "cohort": "HM without documented sepsis",
      "wald_chi_square": 4018.556,
      "degrees_of_freedom": 8,
      "overall_p_value": "<0.001"
    },
    {
      "cohort": "HM with documented sepsis",
      "wald_chi_square": 2423.702,
      "degrees_of_freedom": 8,
      "overall_p_value": "<0.001"
    }
  ],
  "tables": [
    {
      "cohort": "All adult HM hospitalizations",
      "hm_subtype": "Lymphoma",
      "unweighted_sample_n": 301494,
      "unweighted_palliative_care_n": 23491,
      "weighted_hospitalizations": 1507470,
      "weighted_palliative_care_n": 117455,
      "weighted_palliative_care_percent": 7.79,
      "ci_95_lower_percent": 7.7,
      "ci_95_upper_percent": 7.89,
      "overall_p_value": "<0.001"
    },
    {
      "cohort": "All adult HM hospitalizations",
      "hm_subtype": "AML",
      "unweighted_sample_n": 79382,
      "unweighted_palliative_care_n": 10984,
      "weighted_hospitalizations": 396910,
      "weighted_palliative_care_n": 54920,
      "weighted_palliative_care_percent": 13.84,
      "ci_95_lower_percent": 13.6,
      "ci_95_upper_percent": 14.08,
      "overall_p_value": ""
    },
    {
      "cohort": "All adult HM hospitalizations",
      "hm_subtype": "CML",
      "unweighted_sample_n": 26540,
      "unweighted_palliative_care_n": 1760,
      "weighted_hospitalizations": 132700,
      "weighted_palliative_care_n": 8800,
      "weighted_palliative_care_percent": 6.63,
      "ci_95_lower_percent": 6.34,
      "ci_95_upper_percent": 6.94,
      "overall_p_value": ""
    },
    {
      "cohort": "All adult HM hospitalizations",
      "hm_subtype": "CLL/chronic leukemia",
      "unweighted_sample_n": 108837,
      "unweighted_palliative_care_n": 8272,
      "weighted_hospitalizations": 544185,
      "weighted_palliative_care_n": 41360,
      "weighted_palliative_care_percent": 7.6,
      "ci_95_lower_percent": 7.44,
      "ci_95_upper_percent": 7.76,
      "overall_p_value": ""
    },
    {
      "cohort": "All adult HM hospitalizations",
      "hm_subtype": "ALL/unspecified acute leukemia",
      "unweighted_sample_n": 32145,
      "unweighted_palliative_care_n": 2200,
      "weighted_hospitalizations": 160725,
      "weighted_palliative_care_n": 11000,
      "weighted_palliative_care_percent": 6.84,
      "ci_95_lower_percent": 6.57,
      "ci_95_upper_percent": 7.13,
      "overall_p_value": ""
    },
    {
      "cohort": "All adult HM hospitalizations",
      "hm_subtype": "Other leukemia",
      "unweighted_sample_n": 20000,
      "unweighted_palliative_care_n": 2031,
      "weighted_hospitalizations": 100000,
      "weighted_palliative_care_n": 10155,
      "weighted_palliative_care_percent": 10.16,
      "ci_95_lower_percent": 9.74,
      "ci_95_upper_percent": 10.58,
      "overall_p_value": ""
    },
    {
      "cohort": "All adult HM hospitalizations",
      "hm_subtype": "Myeloma/plasma-cell neoplasm",
      "unweighted_sample_n": 150044,
      "unweighted_palliative_care_n": 13580,
      "weighted_hospitalizations": 750220,
      "weighted_palliative_care_n": 67900,
      "weighted_palliative_care_percent": 9.05,
      "ci_95_lower_percent": 8.91,
      "ci_95_upper_percent": 9.2,
      "overall_p_value": ""
    },
    {
      "cohort": "All adult HM hospitalizations",
      "hm_subtype": "MDS",
      "unweighted_sample_n": 106324,
      "unweighted_palliative_care_n": 9809,
      "weighted_hospitalizations": 531620,
      "weighted_palliative_care_n": 49045,
      "weighted_palliative_care_percent": 9.23,
      "ci_95_lower_percent": 9.05,
      "ci_95_upper_percent": 9.4,
      "overall_p_value": ""
    },
    {
      "cohort": "All adult HM hospitalizations",
      "hm_subtype": "MPN",
      "unweighted_sample_n": 170226,
      "unweighted_palliative_care_n": 8606,
      "weighted_hospitalizations": 851130,
      "weighted_palliative_care_n": 43030,
      "weighted_palliative_care_percent": 5.06,
      "ci_95_lower_percent": 4.95,
      "ci_95_upper_percent": 5.16,
      "overall_p_value": ""
    },
    {
      "cohort": "HM without documented sepsis",
      "hm_subtype": "Lymphoma",
      "unweighted_sample_n": 258745,
      "unweighted_palliative_care_n": 15851,
      "weighted_hospitalizations": 1293725,
      "weighted_palliative_care_n": 79255,
      "weighted_palliative_care_percent": 6.13,
      "ci_95_lower_percent": 6.03,
      "ci_95_upper_percent": 6.22,
      "overall_p_value": "<0.001"
    },
    {
      "cohort": "HM without documented sepsis",
      "hm_subtype": "AML",
      "unweighted_sample_n": 63562,
      "unweighted_palliative_care_n": 7137,
      "weighted_hospitalizations": 317810,
      "weighted_palliative_care_n": 35685,
      "weighted_palliative_care_percent": 11.23,
      "ci_95_lower_percent": 10.99,
      "ci_95_upper_percent": 11.48,
      "overall_p_value": ""
    },
    {
      "cohort": "HM without documented sepsis",
      "hm_subtype": "CML",
      "unweighted_sample_n": 23147,
      "unweighted_palliative_care_n": 1215,
      "weighted_hospitalizations": 115735,
      "weighted_palliative_care_n": 6075,
      "weighted_palliative_care_percent": 5.25,
      "ci_95_lower_percent": 4.97,
      "ci_95_upper_percent": 5.54,
      "overall_p_value": ""
    },
    {
      "cohort": "HM without documented sepsis",
      "hm_subtype": "CLL/chronic leukemia",
      "unweighted_sample_n": 91242,
      "unweighted_palliative_care_n": 5459,
      "weighted_hospitalizations": 456210,
      "weighted_palliative_care_n": 27295,
      "weighted_palliative_care_percent": 5.98,
      "ci_95_lower_percent": 5.83,
      "ci_95_upper_percent": 6.14,
      "overall_p_value": ""
    },
    {
      "cohort": "HM without documented sepsis",
      "hm_subtype": "ALL/unspecified acute leukemia",
      "unweighted_sample_n": 27797,
      "unweighted_palliative_care_n": 1517,
      "weighted_hospitalizations": 138985,
      "weighted_palliative_care_n": 7585,
      "weighted_palliative_care_percent": 5.46,
      "ci_95_lower_percent": 5.2,
      "ci_95_upper_percent": 5.73,
      "overall_p_value": ""
    },
    {
      "cohort": "HM without documented sepsis",
      "hm_subtype": "Other leukemia",
      "unweighted_sample_n": 16320,
      "unweighted_palliative_care_n": 1343,
      "weighted_hospitalizations": 81600,
      "weighted_palliative_care_n": 6715,
      "weighted_palliative_care_percent": 8.23,
      "ci_95_lower_percent": 7.82,
      "ci_95_upper_percent": 8.66,
      "overall_p_value": ""
    },
    {
      "cohort": "HM without documented sepsis",
      "hm_subtype": "Myeloma/plasma-cell neoplasm",
      "unweighted_sample_n": 127948,
      "unweighted_palliative_care_n": 9821,
      "weighted_hospitalizations": 639740,
      "weighted_palliative_care_n": 49105,
      "weighted_palliative_care_percent": 7.68,
      "ci_95_lower_percent": 7.53,
      "ci_95_upper_percent": 7.82,
      "overall_p_value": ""
    },
    {
      "cohort": "HM without documented sepsis",
      "hm_subtype": "MDS",
      "unweighted_sample_n": 89579,
      "unweighted_palliative_care_n": 6798,
      "weighted_hospitalizations": 447895,
      "weighted_palliative_care_n": 33990,
      "weighted_palliative_care_percent": 7.59,
      "ci_95_lower_percent": 7.42,
      "ci_95_upper_percent": 7.76,
      "overall_p_value": ""
    },
    {
      "cohort": "HM without documented sepsis",
      "hm_subtype": "MPN",
      "unweighted_sample_n": 138231,
      "unweighted_palliative_care_n": 5631,
      "weighted_hospitalizations": 691155,
      "weighted_palliative_care_n": 28155,
      "weighted_palliative_care_percent": 4.07,
      "ci_95_lower_percent": 3.97,
      "ci_95_upper_percent": 4.18,
      "overall_p_value": ""
    },
    {
      "cohort": "HM with documented sepsis",
      "hm_subtype": "Lymphoma",
      "unweighted_sample_n": 42749,
      "unweighted_palliative_care_n": 7640,
      "weighted_hospitalizations": 213745,
      "weighted_palliative_care_n": 38200,
      "weighted_palliative_care_percent": 17.87,
      "ci_95_lower_percent": 17.51,
      "ci_95_upper_percent": 18.24,
      "overall_p_value": "<0.001"
    },
    {
      "cohort": "HM with documented sepsis",
      "hm_subtype": "AML",
      "unweighted_sample_n": 15820,
      "unweighted_palliative_care_n": 3847,
      "weighted_hospitalizations": 79100,
      "weighted_palliative_care_n": 19235,
      "weighted_palliative_care_percent": 24.32,
      "ci_95_lower_percent": 23.66,
      "ci_95_upper_percent": 24.99,
      "overall_p_value": ""
    },
    {
      "cohort": "HM with documented sepsis",
      "hm_subtype": "CML",
      "unweighted_sample_n": 3393,
      "unweighted_palliative_care_n": 545,
      "weighted_hospitalizations": 16965,
      "weighted_palliative_care_n": 2725,
      "weighted_palliative_care_percent": 16.06,
      "ci_95_lower_percent": 14.87,
      "ci_95_upper_percent": 17.34,
      "overall_p_value": ""
    },
    {
      "cohort": "HM with documented sepsis",
      "hm_subtype": "CLL/chronic leukemia",
      "unweighted_sample_n": 17595,
      "unweighted_palliative_care_n": 2813,
      "weighted_hospitalizations": 87975,
      "weighted_palliative_care_n": 14065,
      "weighted_palliative_care_percent": 15.99,
      "ci_95_lower_percent": 15.45,
      "ci_95_upper_percent": 16.54,
      "overall_p_value": ""
    },
    {
      "cohort": "HM with documented sepsis",
      "hm_subtype": "ALL/unspecified acute leukemia",
      "unweighted_sample_n": 4348,
      "unweighted_palliative_care_n": 683,
      "weighted_hospitalizations": 21740,
      "weighted_palliative_care_n": 3415,
      "weighted_palliative_care_percent": 15.71,
      "ci_95_lower_percent": 14.66,
      "ci_95_upper_percent": 16.82,
      "overall_p_value": ""
    },
    {
      "cohort": "HM with documented sepsis",
      "hm_subtype": "Other leukemia",
      "unweighted_sample_n": 3680,
      "unweighted_palliative_care_n": 688,
      "weighted_hospitalizations": 18400,
      "weighted_palliative_care_n": 3440,
      "weighted_palliative_care_percent": 18.7,
      "ci_95_lower_percent": 17.47,
      "ci_95_upper_percent": 19.99,
      "overall_p_value": ""
    },
    {
      "cohort": "HM with documented sepsis",
      "hm_subtype": "Myeloma/plasma-cell neoplasm",
      "unweighted_sample_n": 22096,
      "unweighted_palliative_care_n": 3759,
      "weighted_hospitalizations": 110480,
      "weighted_palliative_care_n": 18795,
      "weighted_palliative_care_percent": 17.01,
      "ci_95_lower_percent": 16.52,
      "ci_95_upper_percent": 17.51,
      "overall_p_value": ""
    },
    {
      "cohort": "HM with documented sepsis",
      "hm_subtype": "MDS",
      "unweighted_sample_n": 16745,
      "unweighted_palliative_care_n": 3011,
      "weighted_hospitalizations": 83725,
      "weighted_palliative_care_n": 15055,
      "weighted_palliative_care_percent": 17.98,
      "ci_95_lower_percent": 17.41,
      "ci_95_upper_percent": 18.57,
      "overall_p_value": ""
    },
    {
      "cohort": "HM with documented sepsis",
      "hm_subtype": "MPN",
      "unweighted_sample_n": 31995,
      "unweighted_palliative_care_n": 2975,
      "weighted_hospitalizations": 159975,
      "weighted_palliative_care_n": 14875,
      "weighted_palliative_care_percent": 9.3,
      "ci_95_lower_percent": 8.99,
      "ci_95_upper_percent": 9.62,
      "overall_p_value": ""
    }
  ]
}

## All adult HM hospitalizations

| HM subtype | Unweighted sample n | Unweighted palliative-care n | Weighted hospitalizations | Weighted palliative-care n | Weighted palliative-care % | 95% CI lower, % | 95% CI upper, % | Overall p-value |
|---|---|---|---|---|---|---|---|---|
| Lymphoma | 301494 | 23491 | 1507470 | 117455 | 7.79 | 7.7 | 7.89 | <0.001 |
| AML | 79382 | 10984 | 396910 | 54920 | 13.84 | 13.6 | 14.08 |  |
| CML | 26540 | 1760 | 132700 | 8800 | 6.63 | 6.34 | 6.94 |  |
| CLL/chronic leukemia | 108837 | 8272 | 544185 | 41360 | 7.6 | 7.44 | 7.76 |  |
| ALL/unspecified acute leukemia | 32145 | 2200 | 160725 | 11000 | 6.84 | 6.57 | 7.13 |  |
| Other leukemia | 20000 | 2031 | 100000 | 10155 | 10.16 | 9.74 | 10.58 |  |
| Myeloma/plasma-cell neoplasm | 150044 | 13580 | 750220 | 67900 | 9.05 | 8.91 | 9.2 |  |
| MDS | 106324 | 9809 | 531620 | 49045 | 9.23 | 9.05 | 9.4 |  |
| MPN | 170226 | 8606 | 851130 | 43030 | 5.06 | 4.95 | 5.16 |  |
| Total | 994992 | 80733 | 4974958 | 403665 | 8.11 | 8.06 | 8.17 | <0.001 |

## HM without documented sepsis

| HM subtype | Unweighted sample n | Unweighted palliative-care n | Weighted hospitalizations | Weighted palliative-care n | Weighted palliative-care % | 95% CI lower, % | 95% CI upper, % | Overall p-value |
|---|---|---|---|---|---|---|---|---|
| Lymphoma | 258745 | 15851 | 1293725 | 79255 | 6.13 | 6.03 | 6.22 | <0.001 |
| AML | 63562 | 7137 | 317810 | 35685 | 11.23 | 10.99 | 11.48 |  |
| CML | 23147 | 1215 | 115735 | 6075 | 5.25 | 4.97 | 5.54 |  |
| CLL/chronic leukemia | 91242 | 5459 | 456210 | 27295 | 5.98 | 5.83 | 6.14 |  |
| ALL/unspecified acute leukemia | 27797 | 1517 | 138985 | 7585 | 5.46 | 5.2 | 5.73 |  |
| Other leukemia | 16320 | 1343 | 81600 | 6715 | 8.23 | 7.82 | 8.66 |  |
| Myeloma/plasma-cell neoplasm | 127948 | 9821 | 639740 | 49105 | 7.68 | 7.53 | 7.82 |  |
| MDS | 89579 | 6798 | 447895 | 33990 | 7.59 | 7.42 | 7.76 |  |
| MPN | 138231 | 5631 | 691155 | 28155 | 4.07 | 3.97 | 4.18 |  |
| Total | 836571 | 54772 | 4182853 | 273860 | 6.55 | 6.49 | 6.6 | <0.001 |

## HM with documented sepsis

| HM subtype | Unweighted sample n | Unweighted palliative-care n | Weighted hospitalizations | Weighted palliative-care n | Weighted palliative-care % | 95% CI lower, % | 95% CI upper, % | Overall p-value |
|---|---|---|---|---|---|---|---|---|
| Lymphoma | 42749 | 7640 | 213745 | 38200 | 17.87 | 17.51 | 18.24 | <0.001 |
| AML | 15820 | 3847 | 79100 | 19235 | 24.32 | 23.66 | 24.99 |  |
| CML | 3393 | 545 | 16965 | 2725 | 16.06 | 14.87 | 17.34 |  |
| CLL/chronic leukemia | 17595 | 2813 | 87975 | 14065 | 15.99 | 15.45 | 16.54 |  |
| ALL/unspecified acute leukemia | 4348 | 683 | 21740 | 3415 | 15.71 | 14.66 | 16.82 |  |
| Other leukemia | 3680 | 688 | 18400 | 3440 | 18.7 | 17.47 | 19.99 |  |
| Myeloma/plasma-cell neoplasm | 22096 | 3759 | 110480 | 18795 | 17.01 | 16.52 | 17.51 |  |
| MDS | 16745 | 3011 | 83725 | 15055 | 17.98 | 17.41 | 18.57 |  |
| MPN | 31995 | 2975 | 159975 | 14875 | 9.3 | 8.99 | 9.62 |  |
| Total | 158421 | 25961 | 792105 | 129805 | 16.39 | 16.21 | 16.57 | <0.001 |

# Phase 8: Primary Adjusted Model — Commands 16 and 16B

In [8]:
%run notebooks/phase_8_primary_adjusted.ipynb

{
  "outcome": "Documented inpatient palliative-care use (normalized Z515 in any diagnosis position)",
  "included_unweighted_records": 994992,
  "excluded_records": 0,
  "iterations": 8,
  "reference_categories": {
    "sex": "Male",
    "race": "White",
    "payer": "Medicare",
    "income": "0\u201325th percentile",
    "cci_category": "0",
    "region": "Northeast",
    "location_teaching": "Rural",
    "bed_size": "Small",
    "year_category": "2016",
    "hm_subtype_label": "Lymphoma"
  },
  "variance_note": "DISCWT-weighted logistic model with year-specific NIS_STRATUM linearization and discharge-level variance units; not full NIS hospital-cluster-adjusted inference.",
  "primary_results": [
    {
      "measure": "Adjusted odds ratio for documented sepsis",
      "estimate": 2.801,
      "ci_95": "2.756\u20132.848",
      "p_value": "<0.001"
    },
    {
      "measure": "Adjusted absolute probability difference, percentage points",
      "estimate": 9.46,
      "ci_95": "9.27\u20139.65",
      "p_value": "<0.001"
    },
    {
      "measure": "Total",
      "estimate": "\u2014",
      "ci_95": "\u2014",
      "p_value": "\u2014"
    }
  ],
  "adjusted_probabilities": [
    {
      "sepsis_status": "No documented sepsis",
      "adjusted_probability_percent": 6.58,
      "ci_95_lower_percent": 6.53,
      "ci_95_upper_percent": 6.63
    },
    {
      "sepsis_status": "Documented sepsis",
      "adjusted_probability_percent": 16.04,
      "ci_95_lower_percent": 15.86,
      "ci_95_upper_percent": 16.22
    },
    {
      "sepsis_status": "Total observed cohort",
      "adjusted_probability_percent": "\u2014",
      "ci_95_lower_percent": "\u2014",
      "ci_95_upper_percent": "\u2014"
    }
  ]
}

## Primary adjusted results

| Measure | Estimate | 95% CI | P-value |
|---|---|---|---|
| Adjusted odds ratio for documented sepsis | 2.801 | 2.756–2.848 | <0.001 |
| Adjusted absolute probability difference, percentage points | 9.46 | 9.27–9.65 | <0.001 |
| Total | — | — | — |

## Adjusted palliative-care probabilities

| Sepsis status | Adjusted probability, % | 95% CI lower, % | 95% CI upper, % |
|---|---|---|---|
| No documented sepsis | 6.58 | 6.53 | 6.63 |
| Documented sepsis | 16.04 | 15.86 | 16.22 |
| Total observed cohort | — | — | — |

# Phase 9: Sepsis-by-HM-Subtype Interaction — Commands 17A and 17B

In [9]:
%run notebooks/phase_9_interaction.ipynb

{
  "included_unweighted_records": 994992,
  "excluded_records": 0,
  "iterations": 8,
  "joint_interaction_test": {
    "wald_chi_square": 181.245,
    "degrees_of_freedom": 8,
    "overall_interaction_p_value": "<0.001"
  },
  "variance_note": "DISCWT-weighted interaction model with year-specific NIS_STRATUM linearization and discharge-level variance units; not full NIS hospital-cluster-adjusted inference.",
  "subtype_estimates": [
    {
      "hm_subtype": "Lymphoma",
      "adjusted_probability_no_sepsis_percent": 6.53,
      "adjusted_probability_sepsis_percent": 17.86,
      "adjusted_absolute_difference_pp": 11.33,
      "difference_ci_95_lower_pp": 10.96,
      "difference_ci_95_upper_pp": 11.7,
      "subtype_p_value": "<0.001",
      "overall_interaction_p_value": "<0.001"
    },
    {
      "hm_subtype": "AML",
      "adjusted_probability_no_sepsis_percent": 12.53,
      "adjusted_probability_sepsis_percent": 25.59,
      "adjusted_absolute_difference_pp": 13.05,
      "difference_ci_95_lower_pp": 12.32,
      "difference_ci_95_upper_pp": 13.78,
      "subtype_p_value": "<0.001",
      "overall_interaction_p_value": ""
    },
    {
      "hm_subtype": "CML",
      "adjusted_probability_no_sepsis_percent": 5.41,
      "adjusted_probability_sepsis_percent": 15.56,
      "adjusted_absolute_difference_pp": 10.14,
      "difference_ci_95_lower_pp": 8.92,
      "difference_ci_95_upper_pp": 11.37,
      "subtype_p_value": "<0.001",
      "overall_interaction_p_value": ""
    },
    {
      "hm_subtype": "CLL/chronic leukemia",
      "adjusted_probability_no_sepsis_percent": 4.95,
      "adjusted_probability_sepsis_percent": 13.19,
      "adjusted_absolute_difference_pp": 8.24,
      "difference_ci_95_lower_pp": 7.76,
      "difference_ci_95_upper_pp": 8.71,
      "subtype_p_value": "<0.001",
      "overall_interaction_p_value": ""
    },
    {
      "hm_subtype": "ALL/unspecified acute leukemia",
      "adjusted_probability_no_sepsis_percent": 8.79,
      "adjusted_probability_sepsis_percent": 22.31,
      "adjusted_absolute_difference_pp": 13.52,
      "difference_ci_95_lower_pp": 12.05,
      "difference_ci_95_upper_pp": 14.99,
      "subtype_p_value": "<0.001",
      "overall_interaction_p_value": ""
    },
    {
      "hm_subtype": "Other leukemia",
      "adjusted_probability_no_sepsis_percent": 7.76,
      "adjusted_probability_sepsis_percent": 17.31,
      "adjusted_absolute_difference_pp": 9.55,
      "difference_ci_95_lower_pp": 8.31,
      "difference_ci_95_upper_pp": 10.79,
      "subtype_p_value": "<0.001",
      "overall_interaction_p_value": ""
    },
    {
      "hm_subtype": "Myeloma/plasma-cell neoplasm",
      "adjusted_probability_no_sepsis_percent": 7.31,
      "adjusted_probability_sepsis_percent": 15.97,
      "adjusted_absolute_difference_pp": 8.66,
      "difference_ci_95_lower_pp": 8.18,
      "difference_ci_95_upper_pp": 9.15,
      "subtype_p_value": "<0.001",
      "overall_interaction_p_value": ""
    },
    {
      "hm_subtype": "MDS",
      "adjusted_probability_no_sepsis_percent": 6.03,
      "adjusted_probability_sepsis_percent": 14.75,
      "adjusted_absolute_difference_pp": 8.72,
      "difference_ci_95_lower_pp": 8.21,
      "difference_ci_95_upper_pp": 9.23,
      "subtype_p_value": "<0.001",
      "overall_interaction_p_value": ""
    },
    {
      "hm_subtype": "MPN",
      "adjusted_probability_no_sepsis_percent": 4.66,
      "adjusted_probability_sepsis_percent": 10.84,
      "adjusted_absolute_difference_pp": 6.19,
      "difference_ci_95_lower_pp": 5.81,
      "difference_ci_95_upper_pp": 6.56,
      "subtype_p_value": "<0.001",
      "overall_interaction_p_value": ""
    },
    {
      "hm_subtype": "Total",
      "adjusted_probability_no_sepsis_percent": "\u2014",
      "adjusted_probability_sepsis_percent": "\u2014",
      "adjusted_absolute_difference_pp": "\u2014",
      "difference_ci_95_lower_pp": "\u2014",
      "difference_ci_95_upper_pp": "\u2014",
      "subtype_p_value": "\u2014",
      "overall_interaction_p_value": "<0.001"
    }
  ]
}

## Joint interaction test

| Measure | Wald chi-square | Degrees of freedom | P-value |
|---|---|---|---|
| Sepsis × HM subtype interaction | 181.245 | 8 | <0.001 |
| Total | — | — | — |

## Subtype-specific adjusted estimates

| HM subtype | Adjusted probability without sepsis, % | Adjusted probability with sepsis, % | Adjusted difference, pp | Difference 95% CI, pp | Subtype p-value | Overall interaction p-value |
|---|---|---|---|---|---|---|
| Lymphoma | 6.53 | 17.86 | 11.33 | 10.96–11.70 | <0.001 | <0.001 |
| AML | 12.53 | 25.59 | 13.05 | 12.32–13.78 | <0.001 |  |
| CML | 5.41 | 15.56 | 10.14 | 8.92–11.37 | <0.001 |  |
| CLL/chronic leukemia | 4.95 | 13.19 | 8.24 | 7.76–8.71 | <0.001 |  |
| ALL/unspecified acute leukemia | 8.79 | 22.31 | 13.52 | 12.05–14.99 | <0.001 |  |
| Other leukemia | 7.76 | 17.31 | 9.55 | 8.31–10.79 | <0.001 |  |
| Myeloma/plasma-cell neoplasm | 7.31 | 15.97 | 8.66 | 8.18–9.15 | <0.001 |  |
| MDS | 6.03 | 14.75 | 8.72 | 8.21–9.23 | <0.001 |  |
| MPN | 4.66 | 10.84 | 6.19 | 5.81–6.56 | <0.001 |  |
| Total | — | — | — | — | — | <0.001 |

# Phase 10: In-Hospital Decedent Analysis — Commands 19A–19C

In [10]:
%run notebooks/phase_10_decedents.ipynb

{
  "died_missing_records": 441,
  "decedent_unweighted_n": 53737,
  "sepsis_decedent_unweighted_n": 27210,
  "command_19a_p_value": "<0.001",
  "command_19b_interaction_test": {
    "wald_chi_square": 18.816,
    "degrees_of_freedom": 8,
    "p_value": "0.016"
  },
  "command_19c_subtype_test": {
    "wald_chi_square": 20.066,
    "degrees_of_freedom": 8,
    "p_value": "0.010"
  },
  "variance_note": "DISCWT-weighted estimates with year-specific NIS_STRATUM linearization and discharge-level variance units; not full NIS hospital-cluster-adjusted inference."
}

## Command 19A

| Cohort | Unweighted sample n | Unweighted palliative-care n | Weighted hospitalizations | Weighted palliative-care n | Weighted palliative-care % | 95% CI lower, % | 95% CI upper, % | P-value |
|---|---|---|---|---|---|---|---|---|
| Decedents without documented sepsis | 26527 | 15179 | 132635 | 75895 | 57.22 | 56.63 | 57.81 | <0.001 |
| Decedents with documented sepsis | 27210 | 13329 | 136050 | 66645 | 48.99 | 48.4 | 49.57 |  |
| Total decedents | 53737 | 28508 | 268685 | 142540 | 53.05 | 52.64 | 53.46 | <0.001 |

## Command 19B

| HM subtype | Adjusted probability without sepsis, % | Adjusted probability with sepsis, % | Adjusted difference, pp | Difference 95% CI, pp | Subtype p-value | Overall interaction p-value |
|---|---|---|---|---|---|---|
| Lymphoma | 59.08 | 50.57 | -8.52 | -10.06–-6.97 | <0.001 | 0.016 |
| AML | 59.47 | 50.12 | -9.35 | -11.52–-7.18 | <0.001 |  |
| CML | 56.39 | 52.5 | -3.89 | -9.15–1.38 | 0.148 |  |
| CLL/chronic leukemia | 54.75 | 47.49 | -7.26 | -9.70–-4.81 | <0.001 |  |
| ALL/unspecified acute leukemia | 55.74 | 47.3 | -8.45 | -13.38–-3.52 | <0.001 |  |
| Other leukemia | 54.89 | 48.89 | -6.0 | -10.90–-1.10 | 0.016 |  |
| Myeloma/plasma-cell neoplasm | 56.66 | 50.39 | -6.27 | -8.42–-4.12 | <0.001 |  |
| MDS | 54.57 | 48.34 | -6.24 | -8.63–-3.84 | <0.001 |  |
| MPN | 51.64 | 48.37 | -3.27 | -5.92–-0.62 | 0.015 |  |
| Total | — | — | — | — | — | 0.016 |

## Command 19C unadjusted

| HM subtype | Unweighted sample n | Unweighted palliative-care n | Weighted hospitalizations | Weighted palliative-care n | Weighted palliative-care % | 95% CI lower, % | 95% CI upper, % | Overall p-value |
|---|---|---|---|---|---|---|---|---|
| Lymphoma | 8317 | 4148 | 41585 | 20740 | 49.87 | 48.81 | 50.94 | 0.002 |
| AML | 4090 | 2068 | 20450 | 10340 | 50.56 | 49.04 | 52.08 |  |
| CML | 601 | 309 | 3005 | 1545 | 51.41 | 47.44 | 55.37 |  |
| CLL/chronic leukemia | 3058 | 1486 | 15290 | 7430 | 48.59 | 46.84 | 50.35 |  |
| ALL/unspecified acute leukemia | 819 | 362 | 4095 | 1810 | 44.2 | 40.84 | 47.61 |  |
| Other leukemia | 768 | 374 | 3840 | 1870 | 48.7 | 45.19 | 52.22 |  |
| Myeloma/plasma-cell neoplasm | 3876 | 1880 | 19380 | 9400 | 48.5 | 46.94 | 50.07 |  |
| MDS | 3004 | 1463 | 15020 | 7315 | 48.7 | 46.92 | 50.48 |  |
| MPN | 2677 | 1239 | 13385 | 6195 | 46.28 | 44.41 | 48.17 |  |
| Total | 27210 | 13329 | 136050 | 66645 | 48.99 | 48.4 | 49.57 | 0.002 |

## Command 19C adjusted

| HM subtype | Adjusted probability, % | 95% CI lower, % | 95% CI upper, % | Overall p-value |
|---|---|---|---|---|
| Lymphoma | 50.04 | 48.99 | 51.1 | 0.010 |
| AML | 49.77 | 48.25 | 51.3 |  |
| CML | 51.76 | 47.87 | 55.66 |  |
| CLL/chronic leukemia | 46.64 | 44.89 | 48.39 |  |
| ALL/unspecified acute leukemia | 47.08 | 43.61 | 50.55 |  |
| Other leukemia | 48.06 | 44.57 | 51.54 |  |
| Myeloma/plasma-cell neoplasm | 49.82 | 48.25 | 51.38 |  |
| MDS | 47.52 | 45.76 | 49.29 |  |
| MPN | 47.85 | 45.98 | 49.73 |  |
| Total | — | — | — | 0.010 |

# Phase 11: Annual Trends — Commands 20A–20C

In [11]:
%run notebooks/phase_11_trends.ipynb

{
  "command_20a_eapc": {
    "eapc_percent": 6.54,
    "ci_95_lower_percent": 6.18,
    "ci_95_upper_percent": 6.91,
    "p_value": "<0.001"
  },
  "command_20b": {
    "no_sepsis_eapc": {
      "eapc_percent": 6.41,
      "ci_95_lower_percent": 5.97,
      "ci_95_upper_percent": 6.85,
      "p_value": "<0.001"
    },
    "sepsis_eapc": {
      "eapc_percent": 5.62,
      "ci_95_lower_percent": 5.02,
      "ci_95_upper_percent": 6.23,
      "p_value": "<0.001"
    },
    "year_by_sepsis_interaction_p_value": "0.039"
  },
  "command_20c": {
    "suppression_threshold": "10 or fewer unweighted palliative-care events",
    "suppressed_cells": 0,
    "year_by_subtype_wald_chi_square": 36.704,
    "degrees_of_freedom": 8,
    "year_by_subtype_interaction_p_value": "<0.001",
    "subtype_trends": [
      {
        "hm_subtype": "Lymphoma",
        "eapc_percent": 4.37,
        "ci_95_lower_percent": 3.32,
        "ci_95_upper_percent": 5.44,
        "p_value": "<0.001",
        "overall_year_by_subtype_p_value": "<0.001"
      },
      {
        "hm_subtype": "AML",
        "eapc_percent": 1.62,
        "ci_95_lower_percent": 0.21,
        "ci_95_upper_percent": 3.05,
        "p_value": "0.024",
        "overall_year_by_subtype_p_value": ""
      },
      {
        "hm_subtype": "CML",
        "eapc_percent": 3.63,
        "ci_95_lower_percent": -0.29,
        "ci_95_upper_percent": 7.72,
        "p_value": "0.070",
        "overall_year_by_subtype_p_value": ""
      },
      {
        "hm_subtype": "CLL/chronic leukemia",
        "eapc_percent": 6.43,
        "ci_95_lower_percent": 4.62,
        "ci_95_upper_percent": 8.27,
        "p_value": "<0.001",
        "overall_year_by_subtype_p_value": ""
      },
      {
        "hm_subtype": "ALL/unspecified acute leukemia",
        "eapc_percent": 1.8,
        "ci_95_lower_percent": -1.61,
        "ci_95_upper_percent": 5.33,
        "p_value": "0.304",
        "overall_year_by_subtype_p_value": ""
      },
      {
        "hm_subtype": "Other leukemia",
        "eapc_percent": 2.05,
        "ci_95_lower_percent": -1.4,
        "ci_95_upper_percent": 5.62,
        "p_value": "0.248",
        "overall_year_by_subtype_p_value": ""
      },
      {
        "hm_subtype": "Myeloma/plasma-cell neoplasm",
        "eapc_percent": 5.73,
        "ci_95_lower_percent": 4.17,
        "ci_95_upper_percent": 7.32,
        "p_value": "<0.001",
        "overall_year_by_subtype_p_value": ""
      },
      {
        "hm_subtype": "MDS",
        "eapc_percent": 4.09,
        "ci_95_lower_percent": 2.42,
        "ci_95_upper_percent": 5.79,
        "p_value": "<0.001",
        "overall_year_by_subtype_p_value": ""
      },
      {
        "hm_subtype": "MPN",
        "eapc_percent": 7.94,
        "ci_95_lower_percent": 5.81,
        "ci_95_upper_percent": 10.11,
        "p_value": "<0.001",
        "overall_year_by_subtype_p_value": ""
      },
      {
        "hm_subtype": "Total",
        "eapc_percent": "\u2014",
        "ci_95_lower_percent": "\u2014",
        "ci_95_upper_percent": "\u2014",
        "p_value": "\u2014",
        "overall_year_by_subtype_p_value": "<0.001"
      }
    ]
  },
  "variance_note": "DISCWT-weighted modified-Poisson models with year-specific NIS_STRATUM linearization and discharge-level variance units; not full NIS hospital-cluster-adjusted inference."
}

Suppressed subtype-year cells: 0
## Command 20A annual rates

| Year | Unweighted sample n | Unweighted palliative-care n | Weighted hospitalizations | Weighted palliative-care n | Weighted palliative-care % | 95% CI lower, % | 95% CI upper, % |
|---|---|---|---|---|---|---|---|
| 2016 | 144171 | 9738 | 720855 | 48690 | 6.75 | 6.63 | 6.89 |
| 2017 | 143704 | 10435 | 718520 | 52175 | 7.26 | 7.13 | 7.4 |
| 2018 | 146473 | 11127 | 732365 | 55635 | 7.6 | 7.46 | 7.73 |
| 2019 | 153047 | 11817 | 765235 | 59085 | 7.72 | 7.59 | 7.86 |
| 2020 | 140796 | 12071 | 703980 | 60355 | 8.57 | 8.43 | 8.72 |
| 2021 | 141380 | 13119 | 706899 | 65595 | 9.28 | 9.13 | 9.43 |
| 2022 | 125421 | 12426 | 627105 | 62130 | 9.91 | 9.74 | 10.07 |
| Total, 2016–2022 | 994992 | 80733 | 4974958 | 403665 | 8.11 | 8.06 | 8.17 |

## Command 20A EAPC

| Measure | EAPC, % | 95% CI | P-value |
|---|---|---|---|
| Overall EAPC | 6.54 | 6.18–6.91 | <0.001 |
| Total | — | — | — |

## Command 20B trend tests

| Cohort | EAPC, % | 95% CI | Trend p-value | Year × sepsis p-value |
|---|---|---|---|---|
| No documented sepsis | 6.41 | 5.97–6.85 | <0.001 | 0.039 |
| Documented sepsis | 5.62 | 5.02–6.23 | <0.001 |  |
| Total | — | — | — | 0.039 |

## Command 20C annual rates

| HM subtype | 2016 | 2017 | 2018 | 2019 | 2020 | 2021 | 2022 |
|---|---|---|---|---|---|---|---|
| ALL/unspecified acute leukemia | 12.31 | 17.34 | 14.11 | 17.53 | 16.87 | 17.02 | 14.43 |
| AML | 22.98 | 22.92 | 25.43 | 23.53 | 24.45 | 25.36 | 25.37 |
| CLL/chronic leukemia | 13.21 | 13.7 | 14.48 | 14.41 | 17.83 | 19.08 | 17.71 |
| CML | 12.9 | 16.1 | 17.11 | 15.61 | 14.42 | 16.67 | 18.72 |
| Lymphoma | 15.56 | 15.67 | 17.35 | 17.2 | 19.55 | 20.11 | 19.07 |
| MDS | 14.52 | 17.17 | 18.71 | 17.66 | 17.93 | 21.2 | 18.87 |
| MPN | 8.4 | 8.04 | 8.72 | 8.29 | 9.77 | 10.81 | 17.24 |
| Myeloma/plasma-cell neoplasm | 14.75 | 15.13 | 15.07 | 16.43 | 18.18 | 19.99 | 19.23 |
| Other leukemia | 17.4 | 18.01 | 18.2 | 17.88 | 20.46 | 19.18 | 19.44 |
| Total | 13.94 | 14.75 | 15.67 | 15.55 | 17.04 | 18.48 | 19.34 |

## Command 20C trend tests

| HM subtype | EAPC, % | 95% CI lower, % | 95% CI upper, % | Trend p-value | Overall year × subtype p-value |
|---|---|---|---|---|---|
| Lymphoma | 4.37 | 3.32 | 5.44 | <0.001 | <0.001 |
| AML | 1.62 | 0.21 | 3.05 | 0.024 |  |
| CML | 3.63 | -0.29 | 7.72 | 0.070 |  |
| CLL/chronic leukemia | 6.43 | 4.62 | 8.27 | <0.001 |  |
| ALL/unspecified acute leukemia | 1.8 | -1.61 | 5.33 | 0.304 |  |
| Other leukemia | 2.05 | -1.4 | 5.62 | 0.248 |  |
| Myeloma/plasma-cell neoplasm | 5.73 | 4.17 | 7.32 | <0.001 |  |
| MDS | 4.09 | 2.42 | 5.79 | <0.001 |  |
| MPN | 7.94 | 5.81 | 10.11 | <0.001 |  |
| Total | — | — | — | — | <0.001 |

# End of Consolidated Analysis

The narrative report is maintained in `report.md`. The phase notebooks remain available as smaller review checkpoints, but this master notebook is the recommended single entry point.