# Complications by documented sepsis status

This analysis compares adult HM discharges with documented `A41*` sepsis against adult HM discharges without `A41*`. Diagnosis codes establish co-documentation during the hospitalization, not temporal order or causation.

In [1]:
from pathlib import Path
import os
import sys
import pandas as pd
from IPython.display import Markdown, display

repo_root = Path.cwd()
if not (repo_root / 'src').is_dir():
    repo_root = repo_root.parent
os.chdir(repo_root)
sys.path.insert(0, str(repo_root))
from src.phase_4_complications import main
summary = main()
output_dir = repo_root / 'outputs/phase_4'

{
  "unit": "NIS inpatient discharge, not unique patient",
  "exposure": "Documented sepsis defined by A41* in any diagnosis position",
  "interpretation": "Complications are co-documented during the same hospitalization; temporal order is not available.",
  "inference_note": "P-values use unweighted sampled discharge counts and do not account for hospital clustering; FDR-adjusted values control multiplicity across the displayed complication comparisons.",
  "no_sepsis_unweighted_n": 836571,
  "sepsis_unweighted_n": 158421,
  "largest_absolute_differences": [
    {
      "complication": "Severe sepsis, with or without shock",
      "no_sepsis_unweighted_n": 3692,
      "no_sepsis_weighted_n": 18460,
      "no_sepsis_weighted_percent": 0.44,
      "sepsis_unweighted_n": 67538,
      "sepsis_weighted_n": 337690,
      "sepsis_weighted_percent": 42.63,
      "absolute_difference_percentage_points": 42.19,
      "prevalence_ratio": 96.6,
      "p_value_unadjusted": "<0.001",
      "p_value_fdr_adjusted": "<0.001",
      "fdr_significant_at_0_05": true
    },
    {
      "complication": "Pneumonia",
      "no_sepsis_unweighted_n": 102930,
      "no_sepsis_weighted_n": 514650,
      "no_sepsis_weighted_percent": 12.3,
      "sepsis_unweighted_n": 63040,
      "sepsis_weighted_n": 315200,
      "sepsis_weighted_percent": 39.79,
      "absolute_difference_percentage_points": 27.49,
      "prevalence_ratio": 3.23,
      "p_value_unadjusted": "<0.001",
      "p_value_fdr_adjusted": "<0.001",
      "fdr_significant_at_0_05": true
    },
    {
      "complication": "Severe sepsis with septic shock",
      "no_sepsis_unweighted_n": 2134,
      "no_sepsis_weighted_n": 10670,
      "no_sepsis_weighted_percent": 0.26,
      "sepsis_unweighted_n": 41137,
      "sepsis_weighted_n": 205685,
      "sepsis_weighted_percent": 25.97,
      "absolute_difference_percentage_points": 25.71,
      "prevalence_ratio": 101.8,
      "p_value_unadjusted": "<0.001",
      "p_value_fdr_adjusted": "<0.001",
      "fdr_significant_at_0_05": true
    },
    {
      "complication": "Acute kidney injury",
      "no_sepsis_unweighted_n": 184124,
      "no_sepsis_weighted_n": 920620,
      "no_sepsis_weighted_percent": 22.01,
      "sepsis_unweighted_n": 70212,
      "sepsis_weighted_n": 351060,
      "sepsis_weighted_percent": 44.32,
      "absolute_difference_percentage_points": 22.31,
      "prevalence_ratio": 2.01,
      "p_value_unadjusted": "<0.001",
      "p_value_fdr_adjusted": "<0.001",
      "fdr_significant_at_0_05": true
    },
    {
      "complication": "Acute respiratory failure",
      "no_sepsis_unweighted_n": 72064,
      "no_sepsis_weighted_n": 360320,
      "no_sepsis_weighted_percent": 8.61,
      "sepsis_unweighted_n": 47094,
      "sepsis_weighted_n": 235470,
      "sepsis_weighted_percent": 29.73,
      "absolute_difference_percentage_points": 21.11,
      "prevalence_ratio": 3.45,
      "p_value_unadjusted": "<0.001",
      "p_value_fdr_adjusted": "<0.001",
      "fdr_significant_at_0_05": true
    }
  ]
}

## Coding notes

- Severe sepsis includes `R65.2*`; septic shock is separately identified by `R65.21`.
- Atrial fibrillation/flutter includes `I48*` but excludes chronic AF (`I48.2*`).
- Pulmonary embolism and acute lower-extremity DVT use the exact codes specified in the protocol.
- Categories can overlap; percentages should not be summed.
- Weighted counts are cumulative national discharge estimates for 2016–2022, not unique patients.
- P-values are approximate two-sided two-proportion tests using unweighted sampled discharge counts. They do not account for hospital clustering. Benjamini–Hochberg FDR-adjusted p-values address multiple testing across the displayed complications.

In [2]:
complications = pd.read_csv(output_dir / 'complications_by_sepsis.csv')
complications.loc[len(complications)] = {'complication': 'Total cohort denominator', 'no_sepsis_unweighted_n': summary['no_sepsis_unweighted_n'], 'no_sepsis_weighted_n': '4,182,853', 'no_sepsis_weighted_percent': '100.00', 'sepsis_unweighted_n': summary['sepsis_unweighted_n'], 'sepsis_weighted_n': '792,105', 'sepsis_weighted_percent': '100.00', 'absolute_difference_percentage_points': '—', 'prevalence_ratio': '—', 'p_value_unadjusted': '—', 'p_value_fdr_adjusted': '—', 'fdr_significant_at_0_05': '—'}
display(Markdown('## Table. Co-documented complications by sepsis status'))
display(complications)
print('Copy/paste CSV:\n' + complications.to_csv(index=False))

## Table. Co-documented complications by sepsis status

,complication,no_sepsis_unweighted_n,no_sepsis_weighted_n,no_sepsis_weighted_percent,sepsis_unweighted_n,sepsis_weighted_n,sepsis_weighted_percent,absolute_difference_percentage_points,prevalence_ratio,p_value_unadjusted,p_value_fdr_adjusted,fdr_significant_at_0_05
0,Severe sepsis with septic shock,2134,10670,0.26,41137,205685,25.97,25.71,101.8,<0.001,<0.001,True
1,"Severe sepsis, with or without shock",3692,18460,0.44,67538,337690,42.63,42.19,96.6,<0.001,<0.001,True
2,Acute respiratory failure,72064,360320,8.61,47094,235470,29.73,21.11,3.45,<0.001,<0.001,True
3,"Respiratory failure, unspecified",5289,26445,0.63,2797,13985,1.77,1.13,2.79,<0.001,<0.001,True
4,Acute kidney injury,184124,920620,22.01,70212,351060,44.32,22.31,2.01,<0.001,<0.001,True
5,Pneumonia,102930,514650,12.3,63040,315200,39.79,27.49,3.23,<0.001,<0.001,True
6,Pulmonary embolism,15824,79120,1.89,3395,16975,2.14,0.25,1.13,<0.001,<0.001,True
7,Acute lower-extremity DVT,7160,35800,0.86,1695,8475,1.07,0.21,1.25,<0.001,<0.001,True
8,Tumor lysis syndrome,11841,59205,1.42,3942,19710,2.49,1.07,1.76,<0.001,<0.001,True
9,Disseminated intravascular coagulation,3795,18975,0.45,3072,15360,1.94,1.49,4.27,<0.001,<0.001,True
10,Paroxysmal tachycardia/SVT/VT,26985,134925,3.23,9832,49160,6.21,2.98,1.92,<0.001,<0.001,True
11,"Atrial fibrillation/flutter, excluding chronic AF",145281,726405,17.37,34061,170305,21.5,4.13,1.24,<0.001,<0.001,True
12,Other cardiac arrhythmias,20641,103205,2.47,3723,18615,2.35,-0.12,0.95,0.006,0.006,True
13,Any specified cardiac arrhythmia,172215,861075,20.59,41803,209015,26.39,5.8,1.28,<0.001,<0.001,True
14,Total cohort denominator,836571,"4,182,853",100.00,158421,"792,105",100.00,—,—,—,—,—

Copy/paste CSV:
complication,no_sepsis_unweighted_n,no_sepsis_weighted_n,no_sepsis_weighted_percent,sepsis_unweighted_n,sepsis_weighted_n,sepsis_weighted_percent,absolute_difference_percentage_points,prevalence_ratio,p_value_unadjusted,p_value_fdr_adjusted,fdr_significant_at_0_05
Severe sepsis with septic shock,2134,10670,0.26,41137,205685,25.97,25.71,101.8,<0.001,<0.001,True
"Severe sepsis, with or without shock",3692,18460,0.44,67538,337690,42.63,42.19,96.6,<0.001,<0.001,True
Acute respiratory failure,72064,360320,8.61,47094,235470,29.73,21.11,3.45,<0.001,<0.001,True
"Respiratory failure, unspecified",5289,26445,0.63,2797,13985,1.77,1.13,2.79,<0.001,<0.001,True
Acute kidney injury,184124,920620,22.01,70212,351060,44.32,22.31,2.01,<0.001,<0.001,True
Pneumonia,102930,514650,12.3,63040,315200,39.79,27.49,3.23,<0.001,<0.001,True
Pulmonary embolism,15824,79120,1.89,3395,16975,2.14,0.25,1.13,<0.001,<0.001,True
Acute lower-extremity DVT,7160,35800,0.86,1695,8475,1.07,0.21,1.25,<0.001,<0.001,True
Tumor lysis syndrome,11841,59205,1.42,3942,19710,2.49,1.07,1.76,<0.001,<0.001,True
Disseminated intravascular coagulation,3795,18975,0.45,3072,15360,1.94,1.49,4.27,<0.001,<0.001,True
Paroxysmal tachycardia/SVT/VT,26985,134925,3.23,9832,49160,6.21,2.98,1.92,<0.001,<0.001,True
"Atrial fibrillation/flutter, excluding chronic AF",145281,726405,17.37,34061,170305,21.5,4.13,1.24,<0.001,<0.001,True
Other cardiac arrhythmias,20641,103205,2.47,3723,18615,2.35,-0.12,0.95,0.006,0.006,True
Any specified cardiac arrhythmia,172215,861075,20.59,41803,209015,26.39,5.8,1.28,<0.001,<0.001,True
Total cohort denominator,836571,"4,182,853",100.00,158421,"792,105",100.00,—,—,—,—,—

In [3]:
largest = pd.DataFrame(summary['largest_absolute_differences'])[[
    'complication', 'no_sepsis_weighted_percent',
    'sepsis_weighted_percent', 'absolute_difference_percentage_points'
]]
display(Markdown('## Largest absolute prevalence differences'))
largest.loc[len(largest)] = {'complication': 'Total cohort denominator', 'no_sepsis_weighted_percent': '100.00', 'sepsis_weighted_percent': '100.00', 'absolute_difference_percentage_points': '—'}
display(largest)

## Largest absolute prevalence differences

,complication,no_sepsis_weighted_percent,sepsis_weighted_percent,absolute_difference_percentage_points
0,"Severe sepsis, with or without shock",0.44,42.63,42.19
1,Pneumonia,12.3,39.79,27.49
2,Severe sepsis with septic shock,0.26,25.97,25.71
3,Acute kidney injury,22.01,44.32,22.31
4,Acute respiratory failure,8.61,29.73,21.11
5,Total cohort denominator,100.00,100.00,—

In [4]:
top = summary['largest_absolute_differences'][0]
report_text = f"""## Copy/paste interpretation

Among adult hematologic-malignancy inpatient discharges, the largest absolute difference among the evaluated co-documented complications was observed for {top['complication'].lower()}: {top['sepsis_weighted_percent']:.2f}% among discharges with documented sepsis versus {top['no_sepsis_weighted_percent']:.2f}% among discharges without documented sepsis, an absolute difference of {top['absolute_difference_percentage_points']:.2f} percentage points. These diagnosis-based findings do not establish whether a complication preceded or followed sepsis.
"""
display(Markdown(report_text))
print(report_text)

## Copy/paste interpretation

Among adult hematologic-malignancy inpatient discharges, the largest absolute difference among the evaluated co-documented complications was observed for severe sepsis, with or without shock: 42.63% among discharges with documented sepsis versus 0.44% among discharges without documented sepsis, an absolute difference of 42.19 percentage points. These diagnosis-based findings do not establish whether a complication preceded or followed sepsis.

## Copy/paste interpretation

Among adult hematologic-malignancy inpatient discharges, the largest absolute difference among the evaluated co-documented complications was observed for severe sepsis, with or without shock: 42.63% among discharges with documented sepsis versus 0.44% among discharges without documented sepsis, an absolute difference of 42.19 percentage points. These diagnosis-based findings do not establish whether a complication preceded or followed sepsis.