# Phase 3: baseline characteristics by documented sepsis status

This notebook compares adult hematologic-malignancy inpatient discharges with versus without documented sepsis (`A41*`). Results are discharge-level and survey-weighted with `DISCWT`. Choose **Run → Run All Cells** to refresh every output.

In [1]:
from pathlib import Path
import json
import os
import sys
import pandas as pd
from IPython.display import Markdown, display

repo_root = Path.cwd()
if not (repo_root / 'src').is_dir():
    repo_root = repo_root.parent
if not (repo_root / 'src/phase_3.py').is_file():
    raise RuntimeError('Open this notebook from the IPC-MPC-Study repository.')
os.chdir(repo_root)
sys.path.insert(0, str(repo_root))
from src.phase_3 import main
summary = main()
output_dir = repo_root / 'outputs/phase_3'

{
  "unit": "NIS inpatient discharge, not unique patient",
  "no_sepsis_unweighted_n": 836571,
  "no_sepsis_weighted_n": 4182853,
  "sepsis_unweighted_n": 158421,
  "sepsis_weighted_n": 792105,
  "age_no_sepsis_mean_sd": "66.84 (16.35)",
  "age_sepsis_mean_sd": "67.33 (15.61)",
  "largest_absolute_standardized_differences": [
    {
      "characteristic": "Hospital region (stratum-derived)",
      "level": "West",
      "standardized_difference": 0.102
    },
    {
      "characteristic": "HM subtype",
      "level": "Myeloproliferative neoplasm",
      "standardized_difference": 0.095
    },
    {
      "characteristic": "HM subtype",
      "level": "Lymphoma",
      "standardized_difference": -0.087
    },
    {
      "characteristic": "HM subtype",
      "level": "Acute myeloid leukemia",
      "standardized_difference": 0.084
    },
    {
      "characteristic": "Primary payer",
      "level": "Private insurance",
      "standardized_difference": -0.079
    },
    {
      "characteristic": "Hospital ownership/control (stratum-derived)",
      "level": "Government, nonfederal",
      "standardized_difference": -0.061
    },
    {
      "characteristic": "Sex",
      "level": "Male",
      "standardized_difference": 0.059
    },
    {
      "characteristic": "Sex",
      "level": "Female",
      "standardized_difference": -0.059
    }
  ],
  "limitations": [
    "Descriptive weighted estimates; no adjusted causal interpretation.",
    "HM and A41-only sepsis phenotypes remain draft pending investigator review.",
    "Hospital characteristics are decoded from NIS_STRATUM.",
    "Comorbidity burden is deferred until a validated Charlson or Elixhauser method is selected."
  ]
}

## Definitions and interpretation

- **Population:** adult inpatient discharges with a draft qualifying HM diagnosis in any diagnosis position.
- **Exposure groups:** documented sepsis (`A41*`) versus no `A41*` code.
- **Weighted n:** cumulative national discharge estimate across 2016–2022, not unique patients.
- **Standardized difference:** descriptive group imbalance; positive values indicate a higher value or proportion in the sepsis group. Absolute values around 0.10 or greater are commonly treated as potentially meaningful imbalance.
- **Hospital variables:** decoded from the four-digit `NIS_STRATUM`.

In [2]:
cohort_summary = pd.DataFrame([
    {'group': 'No documented sepsis', 'unweighted_n': summary['no_sepsis_unweighted_n'], 'weighted_n_2016_2022': summary['no_sepsis_weighted_n']},
    {'group': 'Documented sepsis (A41*)', 'unweighted_n': summary['sepsis_unweighted_n'], 'weighted_n_2016_2022': summary['sepsis_weighted_n']},
])
display(Markdown('## Cohort sizes'))
display(cohort_summary)
print('Copy/paste CSV:\n' + cohort_summary.to_csv(index=False))

## Cohort sizes

                      group  unweighted_n  weighted_n_2016_2022
0      No documented sepsis        836571               4182853
1  Documented sepsis (A41*)        158421                792105

Copy/paste CSV:
group,unweighted_n,weighted_n_2016_2022
No documented sepsis,836571,4182853
Documented sepsis (A41*),158421,792105

In [3]:
table_1 = pd.read_csv(output_dir / 'table_1_baseline_characteristics.csv')
display(Markdown('## Table 1. Weighted baseline characteristics by documented sepsis status'))
display(table_1)
print('Copy/paste CSV:\n' + table_1.to_csv(index=False))

## Table 1. Weighted baseline characteristics by documented sepsis status

,characteristic,level,no_sepsis_unweighted_n,no_sepsis_weighted_n,no_sepsis_weighted_percent_or_mean_sd,sepsis_unweighted_n,sepsis_weighted_n,sepsis_weighted_percent_or_mean_sd,difference_percentage_points,standardized_difference
0,"Age, years",Weighted mean (SD),836571,4182853,66.84 (16.35),158421,792105,67.33 (15.61),NaN,0.031
1,Age group,18–59,227633,1138165,27.21%,40925,204625,25.83%,-1.38,-0.031
2,Age group,60 or older,608938,3044689,72.79%,117496,587480,74.17%,1.38,0.031
3,Sex,Male,457091,2285454,54.64%,91204,456020,57.57%,2.93,0.059
4,Sex,Female,379264,1896319,45.34%,67187,335935,42.41%,-2.93,-0.059
5,Sex,Missing,216,1080,0.03%,30,150,0.02%,-0.01,-0.005
6,Race/ethnicity,White,589978,2949889,70.52%,107641,538205,67.95%,-2.58,-0.056
7,Race/ethnicity,Black,102337,511685,12.23%,19933,99665,12.58%,0.35,0.011
8,Race/ethnicity,Hispanic,72158,360790,8.63%,15864,79320,10.01%,1.39,0.048
9,Race/ethnicity,Asian/Pacific Islander,22147,110735,2.65%,5375,26875,3.39%,0.75,0.044
10,Race/ethnicity,Native American,3288,16440,0.39%,800,4000,0.50%,0.11,0.017
11,Race/ethnicity,Other,24313,121565,2.91%,4784,23920,3.02%,0.11,0.007
12,Race/ethnicity,Missing,22350,111750,2.67%,4024,20120,2.54%,-0.13,-0.008
13,Primary payer,Medicare,516994,2584969,61.80%,101172,505860,63.86%,2.06,0.043
14,Primary payer,Medicaid,81171,405855,9.70%,17348,86740,10.95%,1.25,0.041
15,Primary payer,Private insurance,196962,984810,23.54%,32156,160780,20.30%,-3.25,-0.079
16,Primary payer,Self-pay,17788,88940,2.13%,3285,16425,2.07%,-0.05,-0.004
17,Primary payer,No charge,2008,10040,0.24%,339,1695,0.21%,-0.03,-0.005
18,Primary payer,Other,20674,103370,2.47%,3957,19785,2.50%,0.03,0.002
19,Primary payer,Missing,974,4870,0.12%,164,820,0.10%,-0.01,-0.004
20,Median household-income quartile,0–25th percentile,204997,1024985,24.50%,40721,203605,25.70%,1.20,0.028
21,Median household-income quartile,26th–50th percentile,207297,1036485,24.78%,38964,194820,24.60%,-0.18,-0.004
22,Median household-income quartile,51st–75th percentile,208642,1043210,24.94%,38606,193030,24.37%,-0.57,-0.013
23,Median household-income quartile,76th–100th percentile,202425,1012125,24.20%,37508,187540,23.68%,-0.52,-0.012
24,Median household-income quartile,Missing,13210,66050,1.58%,2622,13110,1.66%,0.08,0.006
25,HM subtype,Lymphoma,258745,1293725,30.93%,42749,213745,26.98%,-3.94,-0.087
26,HM subtype,Acute myeloid leukemia,63562,317810,7.60%,15820,79100,9.99%,2.39,0.084
27,HM subtype,Chronic myeloid leukemia,23147,115735,2.77%,3393,16965,2.14%,-0.63,-0.040
28,HM subtype,CLL/chronic leukemia,91242,456210,10.91%,17595,87975,11.11%,0.20,0.006
29,HM subtype,Acute lymphoblastic/unspecified acute leukemia,27797,138985,3.32%,4348,21740,2.74%,-0.58,-0.034
30,HM subtype,Other leukemia,16320,81600,1.95%,3680,18400,2.32%,0.37,0.026
31,HM subtype,Multiple myeloma/plasma-cell neoplasm,127948,639740,15.29%,22096,110480,13.95%,-1.35,-0.038
32,HM subtype,Myelodysplastic disease,89579,447895,10.71%,16745,83725,10.57%,-0.14,-0.004
33,HM subtype,Myeloproliferative neoplasm,138231,691155,16.52%,31995,159975,20.20%,3.67,0.095
34,Hospital region (stratum-derived),Northeast,175549,877745,20.98%,29973,149865,18.92%,-2.06,-0.052
35,Hospital region (stratum-derived),Midwest,195801,979005,23.41%,34122,170610,21.54%,-1.87,-0.045
36,Hospital region (stratum-derived),South,305152,1525760,36.48%,57409,287045,36.24%,-0.24,-0.005
37,Hospital region (stratum-derived),West,160069,800344,19.13%,36917,184585,23.30%,4.17,0.102
38,Hospital location/teaching (stratum-derived),Rural,53101,265505,6.35%,10163,50815,6.42%,0.07,0.003
39,Hospital location/teaching (stratum-derived),Urban nonteaching,132999,664995,15.90%,28687,143435,18.11%,2.21,0.059
40,Hospital location/teaching (stratum-derived),Urban teaching,650471,3252354,77.75%,119571,597855,75.48%,-2.28,-0.054
41,Hospital bed size (stratum-derived),Small,148229,741144,17.72%,29371,146855,18.54%,0.82,0.021
42,Hospital bed size (stratum-derived),Medium,211872,1059359,25.33%,43269,216345,27.31%,1.99,0.045
43,Hospital bed size (stratum-derived),Large,476470,2382351,56.96%,85781,428905,54.15%,-2.81,-0.057
44,Hospital ownership/control (stratum-derived),"Government, nonfederal",109420,547099,13.08%,17565,87825,11.09%,-1.99,-0.061
45,Hospital ownership/control (stratum-derived),"Private, not-for-profit",643158,3215790,76.88%,122493,612465,77.32%,0.44,0.010
46,Hospital ownership/control (stratum-derived),"Private, investor-owned",83993,419965,10.04%,18363,91815,11.59%,1.55,0.050
47,Admission year,2016,122729,613645,14.67%,21442,107210,13.53%,-1.14,-0.033
48,Admission year,2017,121970,609850,14.58%,21734,108670,13.72%,-0.86,-0.025
49,Admission year,2018,123375,616875,14.75%,23098,115490,14.58%,-0.17,-0.005
50,Admission year,2019,128636,643180,15.38%,24411,122055,15.41%,0.03,0.001
51,Admission year,2020,117010,585050,13.99%,23786,118930,15.01%,1.03,0.029
52,Admission year,2021,118005,590025,14.11%,23375,116875,14.75%,0.65,0.018
53,Admission year,2022,104846,524230,12.53%,20575,102875,12.99%,0.45,0.014

Copy/paste CSV:
characteristic,level,no_sepsis_unweighted_n,no_sepsis_weighted_n,no_sepsis_weighted_percent_or_mean_sd,sepsis_unweighted_n,sepsis_weighted_n,sepsis_weighted_percent_or_mean_sd,difference_percentage_points,standardized_difference
"Age, years",Weighted mean (SD),836571,4182853,66.84 (16.35),158421,792105,67.33 (15.61),,0.031
Age group,18–59,227633,1138165,27.21%,40925,204625,25.83%,-1.38,-0.031
Age group,60 or older,608938,3044689,72.79%,117496,587480,74.17%,1.38,0.031
Sex,Male,457091,2285454,54.64%,91204,456020,57.57%,2.93,0.059
Sex,Female,379264,1896319,45.34%,67187,335935,42.41%,-2.93,-0.059
Sex,Missing,216,1080,0.03%,30,150,0.02%,-0.01,-0.005
Race/ethnicity,White,589978,2949889,70.52%,107641,538205,67.95%,-2.58,-0.056
Race/ethnicity,Black,102337,511685,12.23%,19933,99665,12.58%,0.35,0.011
Race/ethnicity,Hispanic,72158,360790,8.63%,15864,79320,10.01%,1.39,0.048
Race/ethnicity,Asian/Pacific Islander,22147,110735,2.65%,5375,26875,3.39%,0.75,0.044
Race/ethnicity,Native American,3288,16440,0.39%,800,4000,0.50%,0.11,0.017
Race/ethnicity,Other,24313,121565,2.91%,4784,23920,3.02%,0.11,0.007
Race/ethnicity,Missing,22350,111750,2.67%,4024,20120,2.54%,-0.13,-0.008
Primary payer,Medicare,516994,2584969,61.80%,101172,505860,63.86%,2.06,0.043
Primary payer,Medicaid,81171,405855,9.70%,17348,86740,10.95%,1.25,0.041
Primary payer,Private insurance,196962,984810,23.54%,32156,160780,20.30%,-3.25,-0.079
Primary payer,Self-pay,17788,88940,2.13%,3285,16425,2.07%,-0.05,-0.004
Primary payer,No charge,2008,10040,0.24%,339,1695,0.21%,-0.03,-0.005
Primary payer,Other,20674,103370,2.47%,3957,19785,2.50%,0.03,0.002
Primary payer,Missing,974,4870,0.12%,164,820,0.10%,-0.01,-0.004
Median household-income quartile,0–25th percentile,204997,1024985,24.50%,40721,203605,25.70%,1.2,0.028
Median household-income quartile,26th–50th percentile,207297,1036485,24.78%,38964,194820,24.60%,-0.18,-0.004
Median household-income quartile,51st–75th percentile,208642,1043210,24.94%,38606,193030,24.37%,-0.57,-0.013
Median household-income quartile,76th–100th percentile,202425,1012125,24.20%,37508,187540,23.68%,-0.52,-0.012
Median household-income quartile,Missing,13210,66050,1.58%,2622,13110,1.66%,0.08,0.006
HM subtype,Lymphoma,258745,1293725,30.93%,42749,213745,26.98%,-3.94,-0.087
HM subtype,Acute myeloid leukemia,63562,317810,7.60%,15820,79100,9.99%,2.39,0.084
HM subtype,Chronic myeloid leukemia,23147,115735,2.77%,3393,16965,2.14%,-0.63,-0.04
HM subtype,CLL/chronic leukemia,91242,456210,10.91%,17595,87975,11.11%,0.2,0.006
HM subtype,Acute lymphoblastic/unspecified acute leukemia,27797,138985,3.32%,4348,21740,2.74%,-0.58,-0.034
HM subtype,Other leukemia,16320,81600,1.95%,3680,18400,2.32%,0.37,0.026
HM subtype,Multiple myeloma/plasma-cell neoplasm,127948,639740,15.29%,22096,110480,13.95%,-1.35,-0.038
HM subtype,Myelodysplastic disease,89579,447895,10.71%,16745,83725,10.57%,-0.14,-0.004
HM subtype,Myeloproliferative neoplasm,138231,691155,16.52%,31995,159975,20.20%,3.67,0.095
Hospital region (stratum-derived),Northeast,175549,877745,20.98%,29973,149865,18.92%,-2.06,-0.052
Hospital region (stratum-derived),Midwest,195801,979005,23.41%,34122,170610,21.54%,-1.87,-0.045
Hospital region (stratum-derived),South,305152,1525760,36.48%,57409,287045,36.24%,-0.24,-0.005
Hospital region (stratum-derived),West,160069,800344,19.13%,36917,184585,23.30%,4.17,0.102
Hospital location/teaching (stratum-derived),Rural,53101,265505,6.35%,10163,50815,6.42%,0.07,0.003
Hospital location/teaching (stratum-derived),Urban nonteaching,132999,664995,15.90%,28687,143435,18.11%,2.21,0.059
Hospital location/teaching (stratum-derived),Urban teaching,650471,3252354,77.75%,119571,597855,75.48%,-2.28,-0.054
Hospital bed size (stratum-derived),Small,148229,741144,17.72%,29371,146855,18.54%,0.82,0.021
Hospital bed size (stratum-derived),Medium,211872,1059359,25.33%,43269,216345,27.31%,1.99,0.045
Hospital bed size (stratum-derived),Large,476470,2382351,56.96%,85781,428905,54.15%,-2.81,-0.057
Hospital ownership/control (stratum-derived),"Government, nonfederal",109420,547099,13.08%,17565,87825,11.09%,-1.99,-0.061
Hospital ownership/control (stratum-derived),"Private, not-for-profit",643158,3215790,76.88%,122493,612465,77.32%,0.44,0.01
Hospital ownership/control (stratum-derived),"Private, investor-owned",83993,419965,10.04%,18363,91815,11.59%,1.55,0.05
Admission year,2016,122729,613645,14.67%,21442,107210,13.53%,-1.14,-0.033
Admission year,2017,121970,609850,14.58%,21734,108670,13.72%,-0.86,-0.025
Admission year,2018,123375,616875,14.75%,23098,115490,14.58%,-0.17,-0.005
Admission year,2019,128636,643180,15.38%,24411,122055,15.41%,0.03,0.001
Admission year,2020,117010,585050,13.99%,23786,118930,15.01%,1.03,0.029
Admission year,2021,118005,590025,14.11%,23375,116875,14.75%,0.65,0.018
Admission year,2022,104846,524230,12.53%,20575,102875,12.99%,0.45,0.014

In [4]:
missingness = pd.read_csv(output_dir / 'missingness_review.csv')
display(Markdown('## Missingness review'))
display(missingness)
print('Copy/paste CSV:\n' + missingness.to_csv(index=False))

## Missingness review

,characteristic,no_sepsis_missing_unweighted_n,no_sepsis_missing_weighted_percent,sepsis_missing_unweighted_n,sepsis_missing_weighted_percent
0,Age group,0,0.00,0,0.00
1,Sex,216,0.03,30,0.02
2,Race/ethnicity,22350,2.67,4024,2.54
3,Primary payer,974,0.12,164,0.10
4,Median household-income quartile,13210,1.58,2622,1.66
5,HM subtype,0,0.00,0,0.00
6,Hospital region (stratum-derived),0,0.00,0,0.00
7,Hospital location/teaching (stratum-derived),0,0.00,0,0.00
8,Hospital bed size (stratum-derived),0,0.00,0,0.00
9,Hospital ownership/control (stratum-derived),0,0.00,0,0.00
10,Admission year,0,0.00,0,0.00

Copy/paste CSV:
characteristic,no_sepsis_missing_unweighted_n,no_sepsis_missing_weighted_percent,sepsis_missing_unweighted_n,sepsis_missing_weighted_percent
Age group,0,0.0,0,0.0
Sex,216,0.03,30,0.02
Race/ethnicity,22350,2.67,4024,2.54
Primary payer,974,0.12,164,0.1
Median household-income quartile,13210,1.58,2622,1.66
HM subtype,0,0.0,0,0.0
Hospital region (stratum-derived),0,0.0,0,0.0
Hospital location/teaching (stratum-derived),0,0.0,0,0.0
Hospital bed size (stratum-derived),0,0.0,0,0.0
Hospital ownership/control (stratum-derived),0,0.0,0,0.0
Admission year,0,0.0,0,0.0

In [5]:
largest_differences = pd.DataFrame(summary['largest_absolute_standardized_differences'])
display(Markdown('## Largest descriptive differences'))
display(largest_differences)
print('Copy/paste CSV:\n' + largest_differences.to_csv(index=False))

## Largest descriptive differences

,characteristic,level,standardized_difference
0,Hospital region (stratum-derived),West,0.102
1,HM subtype,Myeloproliferative neoplasm,0.095
2,HM subtype,Lymphoma,-0.087
3,HM subtype,Acute myeloid leukemia,0.084
4,Primary payer,Private insurance,-0.079
5,Hospital ownership/control (stratum-derived),"Government, nonfederal",-0.061
6,Sex,Male,0.059
7,Sex,Female,-0.059

Copy/paste CSV:
characteristic,level,standardized_difference
Hospital region (stratum-derived),West,0.102
HM subtype,Myeloproliferative neoplasm,0.095
HM subtype,Lymphoma,-0.087
HM subtype,Acute myeloid leukemia,0.084
Primary payer,Private insurance,-0.079
Hospital ownership/control (stratum-derived),"Government, nonfederal",-0.061
Sex,Male,0.059
Sex,Female,-0.059

In [6]:
report_text = f"""### Copy/paste report text

The draft cohort contained {summary['no_sepsis_unweighted_n'] + summary['sepsis_unweighted_n']:,} sampled adult hematologic-malignancy inpatient discharges from 2016–2022. Documented sepsis was present in {summary['sepsis_unweighted_n']:,} sampled discharges and absent in {summary['no_sepsis_unweighted_n']:,}. The corresponding cumulative weighted discharge estimates were {summary['sepsis_weighted_n']:,} and {summary['no_sepsis_weighted_n']:,}, respectively. Mean age was {summary['age_sepsis_mean_sd']} years among discharges with documented sepsis and {summary['age_no_sepsis_mean_sd']} years among discharges without documented sepsis. Baseline characteristics are descriptive and should not be interpreted causally.
"""
display(Markdown(report_text))
print(report_text)

### Copy/paste report text

The draft cohort contained 994,992 sampled adult hematologic-malignancy inpatient discharges from 2016–2022. Documented sepsis was present in 158,421 sampled discharges and absent in 836,571. The corresponding cumulative weighted discharge estimates were 792,105 and 4,182,853, respectively. Mean age was 67.33 (15.61) years among discharges with documented sepsis and 66.84 (16.35) years among discharges without documented sepsis. Baseline characteristics are descriptive and should not be interpreted causally.

### Copy/paste report text

The draft cohort contained 994,992 sampled adult hematologic-malignancy inpatient discharges from 2016–2022. Documented sepsis was present in 158,421 sampled discharges and absent in 836,571. The corresponding cumulative weighted discharge estimates were 792,105 and 4,182,853, respectively. Mean age was 67.33 (15.61) years among discharges with documented sepsis and 66.84 (16.35) years among discharges without documented sepsis. Baseline characteristics are descriptive and should not be interpreted causally.

## Phase 3 review checkpoint

Review the direction and magnitude of baseline differences and the missingness table before proceeding. Comorbidity burden is not yet included because a validated Charlson-versus-Elixhauser method has not been selected. No adjusted model or causal claim is made in this phase.